"""Release-candidate packables: high-value normal/literature items not yet in IKOP."""
from materials_catalog import _mat


def _lit(key, bulk_prefix, loose_name, label, icon, wsm=None, static_model=None, tags=None):
    return _mat(
        key, bulk_prefix, f"Base.{loose_name}", label, icon, wsm,
        static_model=static_model, tags=tags,
        display_category="Literature", item_type="base:literature",
    )


RELEASE_CANDIDATE_MATERIALS = [
    # --- precious metal ---
    _mat("gold_bar", "GoldBarBulk", "Base.GoldBar", "gold bars", "Ingot_Gold", "GoldBar", static_model="GoldBar",
         tags="base:ignorezombiedensity;base:hasmetal"),
    _mat("small_gold_bar", "SmallGoldBarBulk", "Base.SmallGoldBar", "small gold bars", "Ingot_Gold", "GoldBarSmall",
         static_model="GoldBarSmall", tags="base:ignorezombiedensity;base:hasmetal"),
    _mat("silver_bar", "SilverBarBulk", "Base.SilverBar", "silver bars", "Ingot_Silver", "SilverBar", static_model="SilverBar",
         tags="base:ignorezombiedensity;base:hasmetal"),
    _mat("small_silver_bar", "SmallSilverBarBulk", "Base.SmallSilverBar", "small silver bars", "Ingot_Silver",
         "SilverBarSmall", static_model="SilverBarSmall", tags="base:ignorezombiedensity;base:hasmetal"),
    _mat("gold_scrap", "GoldScrapBulk", "Base.GoldScrap", "gold scrap", "GoldScrap", "GoldScrap", tags="base:hasmetal"),
    _mat("silver_scrap", "SilverScrapBulk", "Base.SilverScrap", "silver scrap", "SilverScrap", "SilverScrap",
         tags="base:hasmetal"),
    _mat("gold_sheet", "GoldSheetBulk", "Base.GoldSheet", "gold sheets", "MetalSheet_Small", "SmallGoldSheet",
         metal_unit=20.0, tags="base:hasmetal;base:ignorezombiedensity"),
    _mat("silver_sheet", "SilverSheetBulk", "Base.SilverSheet", "silver sheets", "MetalSheet_Small", "SmallSilverSheet",
         metal_unit=20.0, tags="base:hasmetal;base:ignorezombiedensity"),
    # --- aluminum ---
    _mat("aluminum", "AluminumBulk", "Base.Aluminum", "aluminum", "Aluminum", "Aluminum", metal_unit=5.0,
         tags="base:hasmetal;base:aluminum"),
    _mat("aluminum_fragments", "AluminumFragmentsBulk", "Base.AluminumFragments", "aluminum fragments", "MetalBits",
         "MetalPieces", metal_unit=5.0, tags="base:hasmetal;base:aluminum"),
    # --- electronics / traps ---
    _mat("motion_sensor", "MotionSensorBulk", "Base.MotionSensor", "motion sensors", "MotionSensor", "MotionSensor",
         metal_unit=7.0, display_category="Electronics"),
    _mat("radio_receiver", "RadioReceiverBulk", "Base.RadioReceiver", "radio receivers", "Receiver", "RadioReceiver_Ground",
         display_category="Electronics"),
    _mat("radio_transmitter", "RadioTransmitterBulk", "Base.RadioTransmitter", "radio transmitters", "Receiver",
         "RadioTransmitter_Ground", display_category="Electronics"),
    _mat("receiver", "ReceiverBulk", "Base.Receiver", "receivers", "Receiver", "Receiver", metal_unit=7.0,
         display_category="Electronics"),
    _mat("scanner_module", "ScannerModuleBulk", "Base.ScannerModule", "scanner modules", "ScannerChip",
         display_category="Electronics"),
    _mat("trigger_crafted", "TriggerCraftedBulk", "Base.TriggerCrafted", "crafted triggers", "TriggerCrafted",
         "CraftedTrigger", metal_unit=7.0, display_category="Electronics"),
    _mat("timer_crafted", "TimerCraftedBulk", "Base.TimerCrafted", "crafted timers", "TimerCrafted", "CraftedTimer",
         metal_unit=10.0, tags="base:hasmetal", display_category="Electronics"),
    _mat("remote_crafted_v1", "RemoteCraftedV1Bulk", "Base.RemoteCraftedV1", "crafted remotes (short range)", "RemoteCrafted",
         "RemoteController", metal_unit=15.0, display_category="Electronics"),
    _mat("remote_crafted_v2", "RemoteCraftedV2Bulk", "Base.RemoteCraftedV2", "crafted remotes (medium range)", "RemoteCrafted",
         "RemoteController", metal_unit=15.0, display_category="Electronics"),
    _mat("remote_crafted_v3", "RemoteCraftedV3Bulk", "Base.RemoteCraftedV3", "crafted remotes (long range)", "RemoteCrafted",
         "RemoteController", metal_unit=15.0, display_category="Electronics"),
    _mat("light_bulb_blue", "LightBulbBlueBulk", "Base.LightBulbBlue", "blue light bulbs", "LightBulb", "LightBulbBlue",
         tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    _mat("light_bulb_red", "LightBulbRedBulk", "Base.LightBulbRed", "red light bulbs", "LightBulb", "LightBulbRed",
         tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    _mat("light_bulb_green", "LightBulbGreenBulk", "Base.LightBulbGreen", "green light bulbs", "LightBulb", "LightBulbGreen",
         tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    _mat("light_bulb_yellow", "LightBulbYellowBulk", "Base.LightBulbYellow", "yellow light bulbs", "LightBulb",
         "LightBulbYellow", tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    _mat("light_bulb_orange", "LightBulbOrangeBulk", "Base.LightBulbOrange", "orange light bulbs", "LightBulb",
         "LightBulbOrange", tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    _mat("light_bulb_purple", "LightBulbPurpleBulk", "Base.LightBulbPurple", "purple light bulbs", "LightBulb",
         "LightBulbPurple", tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    _mat("light_bulb_pink", "LightBulbPinkBulk", "Base.LightBulbPink", "pink light bulbs", "LightBulb", "LightBulbPink",
         tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    _mat("light_bulb_cyan", "LightBulbCyanBulk", "Base.LightBulbCyan", "cyan light bulbs", "LightBulb", "LightBulbCyan",
         tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    _mat("light_bulb_magenta", "LightBulbMagentaBulk", "Base.LightBulbMagenta", "magenta light bulbs", "LightBulb",
         "LightBulbMagenta", tags="base:showcondition;base:hasmetal", display_category="Electronics"),
    # --- frames / tarp ---
    _mat("pack_frame", "PackFrameBulk", "Base.PackFrame", "pack frames", "Framepack_Shelf_Small", "CraftedFrame_Lrg2_Grnd",
         tags="base:hasmetal"),
    _mat("pack_frame_large", "PackFrameLargeBulk", "Base.PackFrameLarge", "large pack frames", "Framepack_Shelf_Large",
         "CraftedFrame_Lrg3_Grnd", tags="base:hasmetal"),
    _mat("tarp", "TarpBulk", "Base.Tarp", "tarps", "TentMaterial", "Tarp", tags="base:isfirefuel;base:isfiretinder"),
    _mat("tarp_piece", "TarpPieceBulk", "Base.TarpPiece", "tarp pieces", "Tarp_Ragged", "TarpPiece",
         tags="base:isfirefuel;base:isfiretinder"),
    # --- hardware / tools ---
    _mat("latch", "LatchBulk", "Base.Latch", "latches", "Latch_Forged", "Latch", static_model="Latch",
         tags="base:hasmetal;base:smeltableironsmall"),
    _mat("drawer", "DrawerBulk", "Base.Drawer", "drawers", "Drawer", "Drawer"),
    _mat("heavy_chain_link", "HeavyChainLinkBulk", "Base.HeavyChainLink", "heavy chain links", "ChainLink",
         "HeavyChainLink", static_model="HeavyChainLink", tags="base:hasmetal;base:smeltableironsmall"),
    _mat("crude_bench_vise", "CrudeBenchViseBulk", "Base.CrudeBenchVise", "crude bench vises", "Clamp_Forged",
         "CrudeBenchVise", static_model="CrudeBenchVise", tags="base:hasmetal", display_category="Tool"),
    _mat("crude_bench_vise_parts", "CrudeBenchVisePartsBulk", "Base.CrudeBenchViseParts", "crude bench vise parts",
         "ClampComponents_Forged", "CrudeBenchViseParts", tags="base:hasmetal", display_category="Tool"),
    _mat("measuring_tape", "MeasuringTapeBulk", "Base.MeasuringTape", "measuring tapes", "MeasuringTape", "MeasuringTape",
         display_category="Tool"),
    _mat("plaster_trowel", "PlasterTrowelBulk", "Base.PlasterTrowel", "plaster trowels", "PlasterTrowel", "PlasterTrowel",
         tags="base:hasmetal;base:plastertrowel", display_category="Tool"),
    # --- masonry / clay ---
    _mat("clay_shingle", "ClayShingleBulk", "Base.ClayShingle", "clay shingles", "ClayShingle_Fired", "ClayShingle",
         static_model="ClayShingle"),
    _mat("clay_tile", "ClayTileBulk", "Base.ClayTile", "clay tiles", "ClayTile_Fired", "ClayTile", static_model="ClayTile"),
    _mat("stone_block", "StoneBlockBulk", "Base.StoneBlock", "stone blocks", "RoughBlock", "StoneBlock", static_model="StoneBlock"),
    _mat("ceramic_crucible_unfired", "CeramicCrucibleUnfiredBulk", "Base.CeramicCrucibleUnfired", "unfired ceramic crucibles",
         "Ceramic_Crucible_Unfired", "CeramicCrucibleUnfired", static_model="CeramicCrucibleUnfired"),
    # --- fiber / leather / fur ---
    _mat("flax_broken", "FlaxBrokenBulk", "Base.FlaxBroken", "broken flax", "Flax_Broken", "FlaxBroken"),
    _mat("flax_heckled", "FlaxHeckledBulk", "Base.FlaxHeckled", "heckled flax", "Flax_Heckled", "FlaxHeckled"),
    _mat("flax_scutched", "FlaxScutchedBulk", "Base.FlaxScutched", "scutched flax", "Flax_Scutched", "FlaxScutched"),
    _mat("hemp_broken", "HempBrokenBulk", "Base.HempBroken", "broken hemp", "Hemp_Broken", "HempBroken"),
    _mat("string", "StringBulk", "Base.String", "string", "String", "String"),
    _mat("brain_tan", "BrainTanBulk", "Base.BrainTan", "brain tan", "BrainTan", "BowlBrainTan", static_model="BowlBrainTan",
         tags="base:braintan"),
    _mat("leather_crude_small", "LeatherCrudeSmallBulk", "Base.Leather_Crude_Small", "small crude leather hides",
         "LeatherHide_Crude", "Leather_Crude_Small", tags="base:leathercrudesmall"),
    _mat("leather_crude_medium", "LeatherCrudeMediumBulk", "Base.Leather_Crude_Medium", "medium crude leather hides",
         "LeatherHide_Crude", "Leather_Crude_Medium", tags="base:leathercrudemedium"),
    _mat("leather_crude_large", "LeatherCrudeLargeBulk", "Base.Leather_Crude_Large", "large crude leather hides",
         "LeatherHide_Crude", "Leather_Crude", tags="base:leathercrudelarge"),
    _mat("fur_tuft_white", "FurTuftWhiteBulk", "Base.FurTuft_White", "white fur tufts", "FurTuft_White", "FurTuft_White",
         display_category="Junk"),
    _mat("fur_tuft_grey", "FurTuftGreyBulk", "Base.FurTuft_Grey", "grey fur tufts", "FurTuft_Grey", "FurTuft_Grey",
         display_category="Junk"),
    _mat("fur_tuft_black", "FurTuftBlackBulk", "Base.FurTuft_Black", "black fur tufts", "FurTuft_Black", "FurTuft_Black",
         display_category="Junk"),
    _mat("fur_tuft_browndark", "FurTuftBrowndarkBulk", "Base.FurTuft_Browndark", "dark brown fur tufts", "FurTuft_Browndark",
         "FurTuft_Browndark", display_category="Junk"),
    _mat("fur_tuft_brownlight", "FurTuftBrownlightBulk", "Base.FurTuft_Brownlight", "light brown fur tufts",
         "FurTuft_Brownlight", "FurTuft_Brownlight", display_category="Junk"),
    _mat("tobacco_dried", "TobaccoDriedBulk", "Base.TobaccoDried", "dried tobacco", "Tobacco_Dried", "TobaccoLeafDried",
         display_category="Tool"),
    # --- binding dirty variants (vanilla only ×12 for strips) ---
    _mat("ripped_sheets_dirty", "RippedSheetsDirtyBulk", "Base.RippedSheetsDirty", "dirty ripped sheets", "RagDirty",
         "RippedSheetsDirty", tags="base:binding;base:isfirefuel;base:isfiretinder", display_category="Household"),
    _mat("alcohol_ripped_sheets", "AlcoholRippedSheetsBulk", "Base.AlcoholRippedSheets", "sterilized ripped sheets", "Rag",
         "RippedSheets", tags="base:binding", display_category="FirstAid"),
    _mat("denim_strips_dirty", "DenimStripsDirtyBulk", "Base.DenimStripsDirty", "dirty denim strips", "DenimStrips",
         "DenimStripsDirty", tags="base:binding;base:isfirefuel;base:isfiretinder"),
    # --- animal parts ---
    _mat("small_animal_bone", "SmallAnimalBoneBulk", "Base.SmallAnimalBone", "small animal bones", "Bones", "Bones_Ground",
         tags="base:smallanimalbone", display_category="AnimalPart"),
    _mat("sharp_bone_fragment", "SharpBoneFragmentBulk", "Base.SharpBoneFragment", "sharp bone fragments", "Bone_Sharpbone",
         "SharpBone", tags="base:animalbone;base:spearhead", display_category="AnimalPart"),
    _mat("herbivore_teeth", "HerbivoreTeethBulk", "Base.HerbivoreTeeth", "herbivore teeth", "Teeth_Mammal", "HerbivoreTeeth",
         display_category="AnimalPart"),
    _mat("pig_tusk", "PigTuskBulk", "Base.PigTusk", "pig tusks", "BoarTusk", "BoarTusk", display_category="AnimalPart"),
    # --- cooking / storage ---
    _mat("box_of_jars", "BoxOfJarsBulk", "Base.BoxOfJars", "boxes of jars", "JarBox", "BoxOfJars", survival_gear=True,
         display_category="Cooking"),
    # --- literature (haul reading material) ---
    _lit("book", "BookBulk", "Book", "books", "Book", "BookClosedGround", static_model="Book", tags="base:hardcover;base:hollowbook"),
    _lit("comic_book", "ComicBookBulk", "ComicBook", "comic books", "ComicBook", "ComicBookGround", static_model="ComicBook",
         tags="base:picturebook"),
    _lit("journal", "JournalBulk", "Journal", "journals", "Notebook", "EmptyNotebook", static_model="EmptyNotebook"),
    _lit("notebook", "NotebookBulk", "Notebook", "notebooks", "Notebook", "EmptyNotebook", static_model="EmptyNotebook",
         tags="base:magazine"),
    _lit("sheet_paper", "SheetPaperBulk", "SheetPaper2", "sheets of paper", "Paper", "SheetOfPaper", static_model="SheetOfPaper"),
]
