"""Wave 2 packables from multi-category pzfans scan. Regenerate via generate_wave2_catalog.py."""
from materials_catalog import _mat

WAVE2_MATERIALS = [
    _mat("w2_bull_skull", "Bull_SkullBulk", "Base.Bull_Skull", "bull skull", "Bull_Skull", wsm="Bull_Skull", display_category="AnimalPart"),
    _mat("w2_calf_skull", "Calf_SkullBulk", "Base.Calf_Skull", "calf skull", "Calf_Skull", wsm="Calf_Skull", display_category="AnimalPart"),
    _mat("w2_chicken_chick_skull", "Chicken_Chick_SkullBulk", "Base.Chicken_Chick_Skull", "chicken chick skull", "Chicken_Chick_Skull", wsm="Chicken_Chick_Skull", display_category="AnimalPart"),
    _mat("w2_chicken_hen_skull", "Chicken_Hen_SkullBulk", "Base.Chicken_Hen_Skull", "chicken hen skull", "Chicken_Hen_Skull", wsm="Chicken_Hen_Skull", display_category="AnimalPart"),
    _mat("w2_chicken_rooster_skull", "Chicken_Rooster_SkullBulk", "Base.Chicken_Rooster_Skull", "chicken rooster skull", "Chicken_Rooster_Skull", wsm="Chicken_Rooster_Skull", display_category="AnimalPart"),
    _mat("w2_cow_skull", "Cow_SkullBulk", "Base.Cow_Skull", "cow skull", "Cow_Skull", wsm="Cow_Skull", display_category="AnimalPart"),
    _mat("w2_deer_doe_skull", "DeerDoe_SkullBulk", "Base.DeerDoe_Skull", "deer doe skull", "DeerDoe_Skull", wsm="DeerDoe_Skull", display_category="AnimalPart"),
    _mat("w2_deer_fawn_skull", "DeerFawn_SkullBulk", "Base.DeerFawn_Skull", "deer fawn skull", "DeerFawn_Skull", wsm="DeerFawn_Skull", display_category="AnimalPart"),
    _mat("w2_deer_stag_skull", "DeerStag_SkullBulk", "Base.DeerStag_Skull", "deer stag skull", "DeerStag_Skull", wsm="DeerStag_Skull", display_category="AnimalPart"),
    _mat("w2_lamb_skull", "Lamb_SkullBulk", "Base.Lamb_Skull", "lamb skull", "Lamb_Skull", wsm="Lamb_Skull", display_category="AnimalPart"),
    _mat("w2_pig_skull", "Pig_SkullBulk", "Base.Pig_Skull", "pig skull", "Pig_Skull", wsm="Pig_Skull", display_category="AnimalPart"),
    _mat("w2_piglet_skull", "Piglet_SkullBulk", "Base.Piglet_Skull", "piglet skull", "Piglet_Skull", wsm="Piglet_Skull", display_category="AnimalPart"),
    _mat("w2_rabbit_kitten_skull", "Rabbit_KittenSkullBulk", "Base.Rabbit_KittenSkull", "rabbit kitten skull", "Rabbit_KittenSkull", wsm="Rabbit_KittenSkull", display_category="AnimalPart"),
    _mat("w2_rabbit_skull", "Rabbit_SkullBulk", "Base.Rabbit_Skull", "rabbit skull", "Rabbit_Skull", wsm="Rabbit_Skull", display_category="AnimalPart"),
    _mat("w2_raccoon_skull", "Raccoon_SkullBulk", "Base.Raccoon_Skull", "raccoon skull", "Raccoon_Skull", wsm="Raccoon_Skull", display_category="AnimalPart"),
    _mat("w2_ram_skull", "Ram_SkullBulk", "Base.Ram_Skull", "ram skull", "Ram_Skull", wsm="Ram_Skull", display_category="AnimalPart"),
    _mat("w2_sheep_skull", "Sheep_SkullBulk", "Base.Sheep_Skull", "sheep skull", "Sheep_Skull", wsm="Sheep_Skull", display_category="AnimalPart"),
    _mat("w2_turkey_poult_skull", "Turkey_PoultSkullBulk", "Base.Turkey_PoultSkull", "turkey poult skull", "Turkey_PoultSkull", wsm="Turkey_PoultSkull", display_category="AnimalPart"),
    _mat("w2_turkey_skull", "Turkey_SkullBulk", "Base.Turkey_Skull", "turkey skull", "Turkey_Skull", wsm="Turkey_Skull", display_category="AnimalPart"),
    _mat("w2_compass_directional", "CompassDirectionalBulk", "Base.CompassDirectional", "compass directional", "CompassDirectional", wsm="CompassDirectional", display_category="Camping"),
    _mat("w2_dry_firestarter_block", "DryFirestarterBlockBulk", "Base.DryFirestarterBlock", "dry firestarter block", "DryFirestarterBlock", wsm="DryFirestarterBlock", display_category="Camping"),
    _mat("w2_insect_repellent", "InsectRepellentBulk", "Base.InsectRepellent", "insect repellent", "InsectRepellent", wsm="InsectRepellent", display_category="Camping", item_type="base:drainable"),
    _mat("w2_magnesium_firestarter", "MagnesiumFirestarterBulk", "Base.MagnesiumFirestarter", "magnesium firestarter", "MagnesiumFirestarter", wsm="MagnesiumFirestarter", display_category="Camping", item_type="base:drainable"),
    _mat("w2_magnesium_shavings", "MagnesiumShavingsBulk", "Base.MagnesiumShavings", "magnesium shavings", "MagnesiumShavings", wsm="MagnesiumShavings", display_category="Camping"),
    _mat("w2_perced_wood", "PercedWoodBulk", "Base.PercedWood", "perced wood", "PercedWood", wsm="PercedWood", display_category="Camping"),
    _mat("w2_spork", "SporkBulk", "Base.Spork", "spork", "Spork", wsm="Spork", display_category="Camping"),
    _mat("w2_water_purification_tablets", "WaterPurificationTabletsBulk", "Base.WaterPurificationTablets", "water purification tablets", "WaterPurificationTablets", wsm="WaterPurificationTablets", display_category="Camping", item_type="base:drainable"),
    _mat("w2_basting_brush", "BastingBrushBulk", "Base.BastingBrush", "basting brush", "BastingBrush", wsm="BastingBrush", display_category="Cooking"),
    _mat("w2_bottle_opener", "BottleOpenerBulk", "Base.BottleOpener", "bottle opener", "BottleOpener", wsm="BottleOpener", display_category="Cooking"),
    _mat("w2_bottle_opener_keychain", "BottleOpener_KeychainBulk", "Base.BottleOpener_Keychain", "bottle opener keychain", "BottleOpener_Keychain", wsm="BottleOpener_Keychain", display_category="Cooking"),
    _mat("w2_ceramic_teacup", "CeramicTeacupBulk", "Base.CeramicTeacup", "ceramic teacup", "CeramicTeacup", wsm="CeramicTeacup", display_category="Cooking"),
    _mat("w2_cheese_grater", "CheeseGraterBulk", "Base.CheeseGrater", "cheese grater", "CheeseGrater", wsm="CheeseGrater", display_category="Cooking"),
    _mat("w2_clay_mug", "ClayMugBulk", "Base.ClayMug", "clay mug", "ClayMug", wsm="ClayMug", display_category="Cooking"),
    _mat("w2_copper_cup", "CopperCupBulk", "Base.CopperCup", "copper cup", "CopperCup", wsm="CopperCup", display_category="Cooking"),
    _mat("w2_corkscrew", "CorkscrewBulk", "Base.Corkscrew", "corkscrew", "Corkscrew", wsm="Corkscrew", display_category="Cooking"),
    _mat("w2_cutting_board_plastic", "CuttingBoardPlasticBulk", "Base.CuttingBoardPlastic", "cutting board plastic", "CuttingBoardPlastic", wsm="CuttingBoardPlastic", display_category="Cooking"),
    _mat("w2_cutting_board_wooden", "CuttingBoardWoodenBulk", "Base.CuttingBoardWooden", "cutting board wooden", "CuttingBoardWooden", wsm="CuttingBoardWooden", display_category="Cooking"),
    _mat("w2_gold_cup", "GoldCupBulk", "Base.GoldCup", "gold cup", "GoldCup", wsm="GoldCup", display_category="Cooking"),
    _mat("w2_grill_brush", "GrillBrushBulk", "Base.GrillBrush", "grill brush", "GrillBrush", wsm="GrillBrush", display_category="Cooking"),
    _mat("w2_kettle", "KettleBulk", "Base.Kettle", "kettle", "Kettle", wsm="Kettle", display_category="Cooking"),
    _mat("w2_kettle_copper", "Kettle_CopperBulk", "Base.Kettle_Copper", "kettle copper", "Kettle_Copper", wsm="Kettle_Copper", display_category="Cooking"),
    _mat("w2_kitchen_tongs", "KitchenTongsBulk", "Base.KitchenTongs", "kitchen tongs", "KitchenTongs", wsm="KitchenTongs", display_category="Cooking"),
    _mat("w2_ladle", "LadleBulk", "Base.Ladle", "ladle", "Ladle", wsm="Ladle", display_category="Cooking"),
    _mat("w2_metal_cup", "MetalCupBulk", "Base.MetalCup", "metal cup", "MetalCup", wsm="MetalCup", display_category="Cooking"),
    _mat("w2_mug_white", "MugWhiteBulk", "Base.MugWhite", "mug white", "MugWhite", wsm="MugWhite", display_category="Cooking"),
    _mat("w2_mugl", "MuglBulk", "Base.Mugl", "mugl", "Mugl", wsm="Mugl", display_category="Cooking"),
    _mat("w2_oven_mitt", "OvenMittBulk", "Base.OvenMitt", "oven mitt", "OvenMitt", wsm="OvenMitt", display_category="Cooking"),
    _mat("w2_p38", "P38Bulk", "Base.P38", "p38", "P38", wsm="P38", display_category="Cooking"),
    _mat("w2_pizza_cutter", "PizzaCutterBulk", "Base.PizzaCutter", "pizza cutter", "PizzaCutter", wsm="PizzaCutter", display_category="Cooking"),
    _mat("w2_plastic_fork", "PlasticForkBulk", "Base.PlasticFork", "plastic fork", "PlasticFork", wsm="PlasticFork", display_category="Cooking"),
    _mat("w2_plastic_knife", "PlasticKnifeBulk", "Base.PlasticKnife", "plastic knife", "PlasticKnife", wsm="PlasticKnife", display_category="Cooking"),
    _mat("w2_plastic_spoon", "PlasticSpoonBulk", "Base.PlasticSpoon", "plastic spoon", "PlasticSpoon", wsm="PlasticSpoon", display_category="Cooking"),
    _mat("w2_plate", "PlateBulk", "Base.Plate", "plate", "Plate", wsm="Plate", display_category="Cooking"),
    _mat("w2_silver_cup", "SilverCupBulk", "Base.SilverCup", "silver cup", "SilverCup", wsm="SilverCup", display_category="Cooking"),
    _mat("w2_skewers_wooden", "SkewersWoodenBulk", "Base.SkewersWooden", "skewers wooden", "SkewersWooden", wsm="SkewersWooden", display_category="Cooking"),
    _mat("w2_spatula", "SpatulaBulk", "Base.Spatula", "spatula", "Spatula", wsm="Spatula", display_category="Cooking"),
    _mat("w2_strainer", "StrainerBulk", "Base.Strainer", "strainer", "Strainer", wsm="Strainer", display_category="Cooking"),
    _mat("w2_teacup", "TeacupBulk", "Base.Teacup", "teacup", "Teacup", wsm="Teacup", display_category="Cooking"),
    _mat("w2_timer", "TimerBulk", "Base.Timer", "timer", "Timer", wsm="Timer", display_category="Cooking"),
    _mat("w2_tin_opener", "TinOpenerBulk", "Base.TinOpener", "tin opener", "TinOpener", wsm="TinOpener", display_category="Cooking"),
    _mat("w2_whisk", "WhiskBulk", "Base.Whisk", "whisk", "Whisk", wsm="Whisk", display_category="Cooking"),
    _mat("w2_wooden_fork", "WoodenForkBulk", "Base.WoodenFork", "wooden fork", "WoodenFork", wsm="WoodenFork", display_category="Cooking"),
    _mat("w2_wooden_spoon", "WoodenSpoonBulk", "Base.WoodenSpoon", "wooden spoon", "WoodenSpoon", wsm="WoodenSpoon", display_category="Cooking"),
    _mat("w2_cordless_phone", "CordlessPhoneBulk", "Base.CordlessPhone", "cordless phone", "CordlessPhone", wsm="CordlessPhone", display_category="Electronics"),
    _mat("w2_earbuds", "EarbudsBulk", "Base.Earbuds", "earbuds", "Earbuds", wsm="Earbuds", display_category="Electronics"),
    _mat("w2_hair_dryer", "HairDryerBulk", "Base.HairDryer", "hair dryer", "HairDryer", wsm="HairDryer", display_category="Electronics"),
    _mat("w2_hair_iron", "HairIronBulk", "Base.HairIron", "hair iron", "HairIron", wsm="HairIron", display_category="Electronics"),
    _mat("w2_headphones", "HeadphonesBulk", "Base.Headphones", "headphones", "Headphones", wsm="Headphones", display_category="Electronics"),
    _mat("w2_home_alarm", "HomeAlarmBulk", "Base.HomeAlarm", "home alarm", "HomeAlarm", wsm="HomeAlarm", display_category="Electronics"),
    _mat("w2_microphone", "MicrophoneBulk", "Base.Microphone", "microphone", "Microphone", wsm="Microphone", display_category="Electronics"),
    _mat("w2_pager", "PagerBulk", "Base.Pager", "pager", "Pager", wsm="Pager", display_category="Electronics"),
    _mat("w2_power_bar", "PowerBarBulk", "Base.PowerBar", "power bar", "PowerBar", wsm="PowerBar", display_category="Electronics"),
    _mat("w2_remote", "RemoteBulk", "Base.Remote", "remote", "Remote", wsm="Remote", display_category="Electronics"),
    _mat("w2_speaker", "SpeakerBulk", "Base.Speaker", "speaker", "Speaker", wsm="Speaker", display_category="Electronics"),
    _mat("w2_video_game", "VideoGameBulk", "Base.VideoGame", "video game", "VideoGame", wsm="VideoGame", display_category="Electronics"),
    _mat("w2_bbqstarter_fluid", "BBQStarterFluidBulk", "Base.BBQStarterFluid", "bbqstarter fluid", "BBQStarterFluid", wsm="BBQStarterFluid", display_category="Household", item_type="base:drainable"),
    _mat("w2_bath_towel", "BathTowelBulk", "Base.BathTowel", "bath towel", "BathTowel", wsm="BathTowel", display_category="Household", item_type="base:drainable"),
    _mat("w2_bath_towel_wet", "BathTowelWetBulk", "Base.BathTowelWet", "bath towel wet", "BathTowelWet", wsm="BathTowelWet", display_category="Household"),
    _mat("w2_bleach", "BleachBulk", "Base.Bleach", "bleach", "Bleach", wsm="Bleach", display_category="Household"),
    _mat("w2_calculator", "CalculatorBulk", "Base.Calculator", "calculator", "Calculator", wsm="Calculator", display_category="Household"),
    _mat("w2_cleaning_liquid2", "CleaningLiquid2Bulk", "Base.CleaningLiquid2", "cleaning liquid2", "CleaningLiquid2", wsm="CleaningLiquid2", display_category="Household"),
    _mat("w2_clipboard", "ClipboardBulk", "Base.Clipboard", "clipboard", "Clipboard", wsm="Clipboard", display_category="Household"),
    _mat("w2_correction_fluid", "CorrectionFluidBulk", "Base.CorrectionFluid", "correction fluid", "CorrectionFluid", wsm="CorrectionFluid", display_category="Household", item_type="base:drainable"),
    _mat("w2_dish_cloth", "DishClothBulk", "Base.DishCloth", "dish cloth", "DishCloth", wsm="DishCloth", display_category="Household", item_type="base:drainable"),
    _mat("w2_dish_cloth_wet", "DishClothWetBulk", "Base.DishClothWet", "dish cloth wet", "DishClothWet", wsm="DishClothWet", display_category="Household"),
    _mat("w2_doily", "DoilyBulk", "Base.Doily", "doily", "Doily", wsm="Doily", display_category="Household"),
    _mat("w2_eraser", "EraserBulk", "Base.Eraser", "eraser", "Eraser", wsm="Eraser", display_category="Household"),
    _mat("w2_extinguisher", "ExtinguisherBulk", "Base.Extinguisher", "extinguisher", "Extinguisher", wsm="Extinguisher", display_category="Household", item_type="base:drainable"),
    _mat("w2_lighter_fluid", "LighterFluidBulk", "Base.LighterFluid", "lighter fluid", "LighterFluid", wsm="LighterFluid", display_category="Household", item_type="base:drainable"),
    _mat("w2_magnifying_glass", "MagnifyingGlassBulk", "Base.MagnifyingGlass", "magnifying glass", "MagnifyingGlass", wsm="MagnifyingGlass", display_category="Household"),
    _mat("w2_marker_black", "MarkerBlackBulk", "Base.MarkerBlack", "marker black", "MarkerBlack", wsm="MarkerBlack", display_category="Household"),
    _mat("w2_marker_blue", "MarkerBlueBulk", "Base.MarkerBlue", "marker blue", "MarkerBlue", wsm="MarkerBlue", display_category="Household"),
    _mat("w2_marker_green", "MarkerGreenBulk", "Base.MarkerGreen", "marker green", "MarkerGreen", wsm="MarkerGreen", display_category="Household"),
    _mat("w2_marker_red", "MarkerRedBulk", "Base.MarkerRed", "marker red", "MarkerRed", wsm="MarkerRed", display_category="Household"),
    _mat("w2_rat_poison", "RatPoisonBulk", "Base.RatPoison", "rat poison", "RatPoison", wsm="RatPoison", display_category="Household", item_type="base:drainable"),
    _mat("w2_scissors_blunt", "ScissorsBluntBulk", "Base.ScissorsBlunt", "scissors blunt", "ScissorsBlunt", wsm="ScissorsBlunt", display_category="Household"),
    _mat("w2_soap2", "Soap2Bulk", "Base.Soap2", "soap2", "Soap2", wsm="Soap2", display_category="Household", item_type="base:drainable"),
    _mat("w2_sponge", "SpongeBulk", "Base.Sponge", "sponge", "Sponge", wsm="Sponge", display_category="Household"),
    _mat("w2_straight_razor", "StraightRazorBulk", "Base.StraightRazor", "straight razor", "StraightRazor", wsm="StraightRazor", display_category="Household"),
    _mat("w2_toilet_brush", "ToiletBrushBulk", "Base.ToiletBrush", "toilet brush", "ToiletBrush", wsm="ToiletBrush", display_category="Household"),
    _mat("w2_umbrella_black", "UmbrellaBlackBulk", "Base.UmbrellaBlack", "umbrella black", "UmbrellaBlack", wsm="UmbrellaBlack", display_category="Household"),
    _mat("w2_umbrella_blue", "UmbrellaBlueBulk", "Base.UmbrellaBlue", "umbrella blue", "UmbrellaBlue", wsm="UmbrellaBlue", display_category="Household"),
    _mat("w2_umbrella_red", "UmbrellaRedBulk", "Base.UmbrellaRed", "umbrella red", "UmbrellaRed", wsm="UmbrellaRed", display_category="Household"),
    _mat("w2_umbrella_tinted", "UmbrellaTINTEDBulk", "Base.UmbrellaTINTED", "umbrella tinted", "UmbrellaTINTED", wsm="UmbrellaTINTED", display_category="Household"),
    _mat("w2_umbrella_white", "UmbrellaWhiteBulk", "Base.UmbrellaWhite", "umbrella white", "UmbrellaWhite", wsm="UmbrellaWhite", display_category="Household"),
    _mat("w2_backgammon_board", "BackgammonBoardBulk", "Base.BackgammonBoard", "backgammon board", "BackgammonBoard", wsm="BackgammonBoard", display_category="Junk"),
    _mat("w2_bell", "BellBulk", "Base.Bell", "bell", "Bell", wsm="Bell", display_category="Junk"),
    _mat("w2_business_card_nolans", "BusinessCard_NolansBulk", "Base.BusinessCard_Nolans", "business card nolans", "BusinessCard_Nolans", wsm="BusinessCard_Nolans", display_category="Literature", item_type="base:literature"),
    _mat("w2_business_card_personal", "BusinessCard_PersonalBulk", "Base.BusinessCard_Personal", "business card personal", "BusinessCard_Personal", wsm="BusinessCard_Personal", display_category="Literature", item_type="base:literature"),
    _mat("w2_camera", "CameraBulk", "Base.Camera", "camera", "Camera", wsm="Camera", display_category="Junk"),
    _mat("w2_camera_disposable", "CameraDisposableBulk", "Base.CameraDisposable", "camera disposable", "CameraDisposable", wsm="CameraDisposable", display_category="Junk"),
    _mat("w2_can_pipe", "CanPipeBulk", "Base.CanPipe", "can pipe", "CanPipe", wsm="CanPipe", display_category="Junk"),
    _mat("w2_card_deck", "CardDeckBulk", "Base.CardDeck", "card deck", "CardDeck", wsm="CardDeck", display_category="Junk"),
    _mat("w2_checker_board", "CheckerBoardBulk", "Base.CheckerBoard", "checker board", "CheckerBoard", wsm="CheckerBoard", display_category="Junk"),
    _mat("w2_cigarette_pack", "CigarettePackBulk", "Base.CigarettePack", "cigarette pack", "CigarettePack", wsm="CigarettePack", display_category="Junk", item_type="base:drainable"),
    _mat("w2_cigarette_rolling_papers", "CigaretteRollingPapersBulk", "Base.CigaretteRollingPapers", "cigarette rolling papers", "CigaretteRollingPapers", wsm="CigaretteRollingPapers", display_category="Junk", item_type="base:drainable"),
    _mat("w2_clay_plate", "ClayPlateBulk", "Base.ClayPlate", "clay plate", "ClayPlate", wsm="ClayPlate", display_category="Junk"),
    _mat("w2_clitter", "ClitterBulk", "Base.Clitter", "clitter", "Clitter", wsm="Clitter", display_category="Junk"),
    _mat("w2_cologne", "CologneBulk", "Base.Cologne", "cologne", "Cologne", wsm="Cologne", display_category="Junk"),
    _mat("w2_crayons", "CrayonsBulk", "Base.Crayons", "crayons", "Crayons", wsm="Crayons", display_category="Junk"),
    _mat("w2_credit_card", "CreditCardBulk", "Base.CreditCard", "credit card", "CreditCard", wsm="CreditCard", display_category="Junk"),
    _mat("w2_credit_card_stolen", "CreditCard_StolenBulk", "Base.CreditCard_Stolen", "credit card stolen", "CreditCard_Stolen", wsm="CreditCard_Stolen", display_category="Junk"),
    _mat("w2_dice", "DiceBulk", "Base.Dice", "dice", "Dice", wsm="Dice", display_category="Junk"),
    _mat("w2_dice_bone", "Dice_BoneBulk", "Base.Dice_Bone", "dice bone", "Dice_Bone", wsm="Dice_Bone", display_category="Junk"),
    _mat("w2_dice_wood", "Dice_WoodBulk", "Base.Dice_Wood", "dice wood", "Dice_Wood", wsm="Dice_Wood", display_category="Junk"),
    _mat("w2_dog_tag_pet_blank", "DogTag_Pet_BlankBulk", "Base.DogTag_Pet_Blank", "dog tag pet blank", "DogTag_Pet_Blank", wsm="DogTag_Pet_Blank", display_category="Junk"),
    _mat("w2_dryer_lint", "DryerLintBulk", "Base.DryerLint", "dryer lint", "DryerLint", wsm="DryerLint", display_category="Junk"),
    _mat("w2_flier", "FlierBulk", "Base.Flier", "flier", "Flier", wsm="Flier", display_category="Literature", item_type="base:literature"),
    _mat("w2_flier_nolans", "Flier_NolansBulk", "Base.Flier_Nolans", "flier nolans", "Flier_Nolans", wsm="Flier_Nolans", display_category="Literature", item_type="base:literature"),
    _mat("w2_frame", "FrameBulk", "Base.Frame", "frame", "Frame", wsm="Frame", display_category="Junk"),
    _mat("w2_game_piece_black", "GamePieceBlackBulk", "Base.GamePieceBlack", "game piece black", "GamePieceBlack", wsm="GamePieceBlack", display_category="Junk"),
    _mat("w2_game_piece_red", "GamePieceRedBulk", "Base.GamePieceRed", "game piece red", "GamePieceRed", wsm="GamePieceRed", display_category="Junk"),
    _mat("w2_game_piece_white", "GamePieceWhiteBulk", "Base.GamePieceWhite", "game piece white", "GamePieceWhite", wsm="GamePieceWhite", display_category="Junk"),
    _mat("w2_generic_mail", "GenericMailBulk", "Base.GenericMail", "generic mail", "GenericMail", wsm="GenericMail", display_category="Literature", item_type="base:literature"),
    _mat("w2_hole_puncher", "HolePuncherBulk", "Base.HolePuncher", "hole puncher", "HolePuncher", wsm="HolePuncher", display_category="Junk"),
    _mat("w2_idcard", "IDcardBulk", "Base.IDcard", "idcard", "IDcard", wsm="IDcard", display_category="Literature", item_type="base:literature"),
    _mat("w2_idcard_blank", "IDcard_BlankBulk", "Base.IDcard_Blank", "idcard blank", "IDcard_Blank", wsm="IDcard_Blank", display_category="Literature", item_type="base:literature"),
    _mat("w2_idcard_female", "IDcard_FemaleBulk", "Base.IDcard_Female", "idcard female", "IDcard_Female", wsm="IDcard_Female", display_category="Literature", item_type="base:literature"),
    _mat("w2_idcard_male", "IDcard_MaleBulk", "Base.IDcard_Male", "idcard male", "IDcard_Male", wsm="IDcard_Male", display_category="Literature", item_type="base:literature"),
    _mat("w2_idcard_stolen", "IDcard_StolenBulk", "Base.IDcard_Stolen", "idcard stolen", "IDcard_Stolen", wsm="IDcard_Stolen", display_category="Literature", item_type="base:literature"),
    _mat("w2_index_card", "IndexCardBulk", "Base.IndexCard", "index card", "IndexCard", wsm="IndexCard", display_category="Literature", item_type="base:literature"),
    _mat("w2_letter_handwritten", "LetterHandwrittenBulk", "Base.LetterHandwritten", "letter handwritten", "LetterHandwritten", wsm="LetterHandwritten", display_category="Literature", item_type="base:literature"),
    _mat("w2_money", "MoneyBulk", "Base.Money", "money", "Money", wsm="Money", display_category="Junk"),
    _mat("w2_note", "NoteBulk", "Base.Note", "note", "Note", wsm="Note", display_category="Literature", item_type="base:literature"),
    _mat("w2_official_document", "OfficialDocumentBulk", "Base.OfficialDocument", "official document", "OfficialDocument", wsm="OfficialDocument", display_category="Literature", item_type="base:literature"),
    _mat("w2_paper_napkins2", "PaperNapkins2Bulk", "Base.PaperNapkins2", "paper napkins2", "PaperNapkins2", wsm="PaperNapkins2", display_category="Junk", item_type="base:drainable"),
    _mat("w2_paperwork", "PaperworkBulk", "Base.Paperwork", "paperwork", "Paperwork", wsm="Paperwork", display_category="Literature", item_type="base:literature"),
    _mat("w2_parking_ticket", "ParkingTicketBulk", "Base.ParkingTicket", "parking ticket", "ParkingTicket", wsm="ParkingTicket", display_category="Literature", item_type="base:literature"),
    _mat("w2_passport", "PassportBulk", "Base.Passport", "passport", "Passport", wsm="Passport", display_category="Literature", item_type="base:literature"),
    _mat("w2_perfume", "PerfumeBulk", "Base.Perfume", "perfume", "Perfume", wsm="Perfume", display_category="Junk"),
    _mat("w2_pinecone", "PineconeBulk", "Base.Pinecone", "pinecone", "Pinecone", wsm="Pinecone", display_category="Junk"),
    _mat("w2_poker_chips", "PokerChipsBulk", "Base.PokerChips", "poker chips", "PokerChips", wsm="PokerChips", display_category="Junk"),
    _mat("w2_press_id", "PressIDBulk", "Base.PressID", "press id", "PressID", wsm="PressID", display_category="Literature", item_type="base:literature"),
    _mat("w2_razor", "RazorBulk", "Base.Razor", "razor", "Razor", wsm="Razor", display_category="Junk"),
    _mat("w2_receipt", "ReceiptBulk", "Base.Receipt", "receipt", "Receipt", wsm="Receipt", display_category="Literature", item_type="base:literature"),
    _mat("w2_scratch_ticket", "ScratchTicketBulk", "Base.ScratchTicket", "scratch ticket", "ScratchTicket", wsm="ScratchTicket", display_category="Literature", item_type="base:literature"),
    _mat("w2_scratch_ticket_loser", "ScratchTicket_LoserBulk", "Base.ScratchTicket_Loser", "scratch ticket loser", "ScratchTicket_Loser", wsm="ScratchTicket_Loser", display_category="Literature", item_type="base:literature"),
    _mat("w2_scratch_ticket_winner", "ScratchTicket_WinnerBulk", "Base.ScratchTicket_Winner", "scratch ticket winner", "ScratchTicket_Winner", wsm="ScratchTicket_Winner", display_category="Literature", item_type="base:literature"),
    _mat("w2_speeding_ticket", "SpeedingTicketBulk", "Base.SpeedingTicket", "speeding ticket", "SpeedingTicket", wsm="SpeedingTicket", display_category="Literature", item_type="base:literature"),
    _mat("w2_splinters", "SplintersBulk", "Base.Splinters", "splinters", "Splinters", wsm="Splinters", display_category="Junk"),
    _mat("w2_stapler", "StaplerBulk", "Base.Stapler", "stapler", "Stapler", wsm="Stapler", display_category="Junk"),
    _mat("w2_staples", "StaplesBulk", "Base.Staples", "staples", "Staples", wsm="Staples", display_category="Junk", item_type="base:drainable"),
    _mat("w2_stock_certificate", "StockCertificateBulk", "Base.StockCertificate", "stock certificate", "StockCertificate", wsm="StockCertificate", display_category="Literature", item_type="base:literature"),
    _mat("w2_straw2", "Straw2Bulk", "Base.Straw2", "straw2", "Straw2", wsm="Straw2", display_category="Junk"),
    _mat("w2_tobacco_chewing", "TobaccoChewingBulk", "Base.TobaccoChewing", "tobacco chewing", "TobaccoChewing", wsm="TobaccoChewing", display_category="Junk", item_type="base:drainable"),
    _mat("w2_tobacco_loose", "TobaccoLooseBulk", "Base.TobaccoLoose", "tobacco loose", "TobaccoLoose", wsm="TobaccoLoose", display_category="Junk", item_type="base:drainable"),
    _mat("w2_toilet_paper", "ToiletPaperBulk", "Base.ToiletPaper", "toilet paper", "ToiletPaper", wsm="ToiletPaper", display_category="Junk", item_type="base:drainable"),
    _mat("w2_toothbrush", "ToothbrushBulk", "Base.Toothbrush", "toothbrush", "Toothbrush", wsm="Toothbrush", display_category="Junk"),
    _mat("w2_toothpaste", "ToothpasteBulk", "Base.Toothpaste", "toothpaste", "Toothpaste", wsm="Toothpaste", display_category="Junk"),
    _mat("w2_tsquare", "TsquareBulk", "Base.Tsquare", "tsquare", "Tsquare", wsm="Tsquare", display_category="Junk"),
    _mat("w2_unusable_metal", "UnusableMetalBulk", "Base.UnusableMetal", "unusable metal", "UnusableMetal", wsm="UnusableMetal", display_category="Junk"),
    _mat("w2_unusable_wood", "UnusableWoodBulk", "Base.UnusableWood", "unusable wood", "UnusableWood", wsm="UnusableWood", display_category="Junk"),
    _mat("w2_book_fancy_bible", "BookFancy_BibleBulk", "Base.BookFancy_Bible", "book fancy bible", "BookFancy_Bible", wsm="BookFancy_Bible", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_classic", "BookFancy_ClassicBulk", "Base.BookFancy_Classic", "book fancy classic", "BookFancy_Classic", wsm="BookFancy_Classic", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_classic_fiction", "BookFancy_ClassicFictionBulk", "Base.BookFancy_ClassicFiction", "book fancy classic fiction", "BookFancy_ClassicFiction", wsm="BookFancy_ClassicFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_classic_nonfiction", "BookFancy_ClassicNonfictionBulk", "Base.BookFancy_ClassicNonfiction", "book fancy classic nonfiction", "BookFancy_ClassicNonfiction", wsm="BookFancy_ClassicNonfiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_history", "BookFancy_HistoryBulk", "Base.BookFancy_History", "book fancy history", "BookFancy_History", wsm="BookFancy_History", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_legal", "BookFancy_LegalBulk", "Base.BookFancy_Legal", "book fancy legal", "BookFancy_Legal", wsm="BookFancy_Legal", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_medical", "BookFancy_MedicalBulk", "Base.BookFancy_Medical", "book fancy medical", "BookFancy_Medical", wsm="BookFancy_Medical", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_military_history", "BookFancy_MilitaryHistoryBulk", "Base.BookFancy_MilitaryHistory", "book fancy military history", "BookFancy_MilitaryHistory", wsm="BookFancy_MilitaryHistory", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_occult", "BookFancy_OccultBulk", "Base.BookFancy_Occult", "book fancy occult", "BookFancy_Occult", wsm="BookFancy_Occult", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_philosophy", "BookFancy_PhilosophyBulk", "Base.BookFancy_Philosophy", "book fancy philosophy", "BookFancy_Philosophy", wsm="BookFancy_Philosophy", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_politics", "BookFancy_PoliticsBulk", "Base.BookFancy_Politics", "book fancy politics", "BookFancy_Politics", wsm="BookFancy_Politics", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fancy_religion", "BookFancy_ReligionBulk", "Base.BookFancy_Religion", "book fancy religion", "BookFancy_Religion", wsm="BookFancy_Religion", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_adventure_non_fiction", "Book_AdventureNonFictionBulk", "Base.Book_AdventureNonFiction", "book adventure non fiction", "Book_AdventureNonFiction", wsm="Book_AdventureNonFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_art", "Book_ArtBulk", "Base.Book_Art", "book art", "Book_Art", wsm="Book_Art", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_baseball", "Book_BaseballBulk", "Base.Book_Baseball", "book baseball", "Book_Baseball", wsm="Book_Baseball", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_bible", "Book_BibleBulk", "Base.Book_Bible", "book bible", "Book_Bible", wsm="Book_Bible", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_biography", "Book_BiographyBulk", "Base.Book_Biography", "book biography", "Book_Biography", wsm="Book_Biography", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_business", "Book_BusinessBulk", "Base.Book_Business", "book business", "Book_Business", wsm="Book_Business", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_childs", "Book_ChildsBulk", "Base.Book_Childs", "book childs", "Book_Childs", wsm="Book_Childs", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_cinema", "Book_CinemaBulk", "Base.Book_Cinema", "book cinema", "Book_Cinema", wsm="Book_Cinema", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_classic", "Book_ClassicBulk", "Base.Book_Classic", "book classic", "Book_Classic", wsm="Book_Classic", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_classic_fiction", "Book_ClassicFictionBulk", "Base.Book_ClassicFiction", "book classic fiction", "Book_ClassicFiction", wsm="Book_ClassicFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_classic_nonfiction", "Book_ClassicNonfictionBulk", "Base.Book_ClassicNonfiction", "book classic nonfiction", "Book_ClassicNonfiction", wsm="Book_ClassicNonfiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_computer", "Book_ComputerBulk", "Base.Book_Computer", "book computer", "Book_Computer", wsm="Book_Computer", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_crime_fiction", "Book_CrimeFictionBulk", "Base.Book_CrimeFiction", "book crime fiction", "Book_CrimeFiction", wsm="Book_CrimeFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fantasy", "Book_FantasyBulk", "Base.Book_Fantasy", "book fantasy", "Book_Fantasy", wsm="Book_Fantasy", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_farming", "Book_FarmingBulk", "Base.Book_Farming", "book farming", "Book_Farming", wsm="Book_Farming", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fashion", "Book_FashionBulk", "Base.Book_Fashion", "book fashion", "Book_Fashion", wsm="Book_Fashion", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_fiction", "Book_FictionBulk", "Base.Book_Fiction", "book fiction", "Book_Fiction", wsm="Book_Fiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_general_non_fiction", "Book_GeneralNonFictionBulk", "Base.Book_GeneralNonFiction", "book general non fiction", "Book_GeneralNonFiction", wsm="Book_GeneralNonFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_general_reference", "Book_GeneralReferenceBulk", "Base.Book_GeneralReference", "book general reference", "Book_GeneralReference", wsm="Book_GeneralReference", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_golf", "Book_GolfBulk", "Base.Book_Golf", "book golf", "Book_Golf", wsm="Book_Golf", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_history", "Book_HistoryBulk", "Base.Book_History", "book history", "Book_History", wsm="Book_History", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_horror", "Book_HorrorBulk", "Base.Book_Horror", "book horror", "Book_Horror", wsm="Book_Horror", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_legal", "Book_LegalBulk", "Base.Book_Legal", "book legal", "Book_Legal", wsm="Book_Legal", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_literary_fiction", "Book_LiteraryFictionBulk", "Base.Book_LiteraryFiction", "book literary fiction", "Book_LiteraryFiction", wsm="Book_LiteraryFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_medical", "Book_MedicalBulk", "Base.Book_Medical", "book medical", "Book_Medical", wsm="Book_Medical", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_military", "Book_MilitaryBulk", "Base.Book_Military", "book military", "Book_Military", wsm="Book_Military", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_military_history", "Book_MilitaryHistoryBulk", "Base.Book_MilitaryHistory", "book military history", "Book_MilitaryHistory", wsm="Book_MilitaryHistory", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_music", "Book_MusicBulk", "Base.Book_Music", "book music", "Book_Music", wsm="Book_Music", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_nature", "Book_NatureBulk", "Base.Book_Nature", "book nature", "Book_Nature", wsm="Book_Nature", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_occult", "Book_OccultBulk", "Base.Book_Occult", "book occult", "Book_Occult", wsm="Book_Occult", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_philosophy", "Book_PhilosophyBulk", "Base.Book_Philosophy", "book philosophy", "Book_Philosophy", wsm="Book_Philosophy", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_policing", "Book_PolicingBulk", "Base.Book_Policing", "book policing", "Book_Policing", wsm="Book_Policing", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_politics", "Book_PoliticsBulk", "Base.Book_Politics", "book politics", "Book_Politics", wsm="Book_Politics", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_quackery", "Book_QuackeryBulk", "Base.Book_Quackery", "book quackery", "Book_Quackery", wsm="Book_Quackery", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_religion", "Book_ReligionBulk", "Base.Book_Religion", "book religion", "Book_Religion", wsm="Book_Religion", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_rich", "Book_RichBulk", "Base.Book_Rich", "book rich", "Book_Rich", wsm="Book_Rich", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_romance", "Book_RomanceBulk", "Base.Book_Romance", "book romance", "Book_Romance", wsm="Book_Romance", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_sad_non_fiction", "Book_SadNonFictionBulk", "Base.Book_SadNonFiction", "book sad non fiction", "Book_SadNonFiction", wsm="Book_SadNonFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_school_textbook", "Book_SchoolTextbookBulk", "Base.Book_SchoolTextbook", "book school textbook", "Book_SchoolTextbook", wsm="Book_SchoolTextbook", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_sci_fi", "Book_SciFiBulk", "Base.Book_SciFi", "book sci fi", "Book_SciFi", wsm="Book_SciFi", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_science", "Book_ScienceBulk", "Base.Book_Science", "book science", "Book_Science", wsm="Book_Science", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_sports", "Book_SportsBulk", "Base.Book_Sports", "book sports", "Book_Sports", wsm="Book_Sports", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_thriller", "Book_ThrillerBulk", "Base.Book_Thriller", "book thriller", "Book_Thriller", wsm="Book_Thriller", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_travel", "Book_TravelBulk", "Base.Book_Travel", "book travel", "Book_Travel", wsm="Book_Travel", display_category="Literature", item_type="base:literature"),
    _mat("w2_book_western", "Book_WesternBulk", "Base.Book_Western", "book western", "Book_Western", wsm="Book_Western", display_category="Literature", item_type="base:literature"),
    _mat("w2_catalog", "CatalogBulk", "Base.Catalog", "catalog", "Catalog", wsm="Catalog", display_category="Literature", item_type="base:literature"),
    _mat("w2_childs_picture_book", "ChildsPictureBookBulk", "Base.ChildsPictureBook", "childs picture book", "ChildsPictureBook", wsm="ChildsPictureBook", display_category="Literature", item_type="base:literature"),
    _mat("w2_comic_book_retail", "ComicBook_RetailBulk", "Base.ComicBook_Retail", "comic book retail", "ComicBook_Retail", wsm="ComicBook_Retail", display_category="Literature", item_type="base:literature"),
    _mat("w2_diary1", "Diary1Bulk", "Base.Diary1", "diary1", "Diary1", wsm="Diary1", display_category="Literature", item_type="base:literature"),
    _mat("w2_diary2", "Diary2Bulk", "Base.Diary2", "diary2", "Diary2", wsm="Diary2", display_category="Literature", item_type="base:literature"),
    _mat("w2_graph_paper", "GraphPaperBulk", "Base.GraphPaper", "graph paper", "GraphPaper", wsm="GraphPaper", display_category="Literature", item_type="base:literature"),
    _mat("w2_hottie_z", "HottieZBulk", "Base.HottieZ", "hottie z", "HottieZ", wsm="HottieZ", display_category="Literature", item_type="base:literature"),
    _mat("w2_hottie_z_new", "HottieZ_NewBulk", "Base.HottieZ_New", "hottie z new", "HottieZ_New", wsm="HottieZ_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_crossword", "MagazineCrosswordBulk", "Base.MagazineCrossword", "magazine crossword", "MagazineCrossword", wsm="MagazineCrossword", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_wordsearch", "MagazineWordsearchBulk", "Base.MagazineWordsearch", "magazine wordsearch", "MagazineWordsearch", wsm="MagazineWordsearch", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_art", "Magazine_ArtBulk", "Base.Magazine_Art", "magazine art", "Magazine_Art", wsm="Magazine_Art", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_art_new", "Magazine_Art_NewBulk", "Base.Magazine_Art_New", "magazine art new", "Magazine_Art_New", wsm="Magazine_Art_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_business", "Magazine_BusinessBulk", "Base.Magazine_Business", "magazine business", "Magazine_Business", wsm="Magazine_Business", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_business_new", "Magazine_Business_NewBulk", "Base.Magazine_Business_New", "magazine business new", "Magazine_Business_New", wsm="Magazine_Business_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_car", "Magazine_CarBulk", "Base.Magazine_Car", "magazine car", "Magazine_Car", wsm="Magazine_Car", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_car_new", "Magazine_Car_NewBulk", "Base.Magazine_Car_New", "magazine car new", "Magazine_Car_New", wsm="Magazine_Car_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_childs", "Magazine_ChildsBulk", "Base.Magazine_Childs", "magazine childs", "Magazine_Childs", wsm="Magazine_Childs", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_childs_new", "Magazine_Childs_NewBulk", "Base.Magazine_Childs_New", "magazine childs new", "Magazine_Childs_New", wsm="Magazine_Childs_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_cinema", "Magazine_CinemaBulk", "Base.Magazine_Cinema", "magazine cinema", "Magazine_Cinema", wsm="Magazine_Cinema", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_cinema_new", "Magazine_Cinema_NewBulk", "Base.Magazine_Cinema_New", "magazine cinema new", "Magazine_Cinema_New", wsm="Magazine_Cinema_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_crime", "Magazine_CrimeBulk", "Base.Magazine_Crime", "magazine crime", "Magazine_Crime", wsm="Magazine_Crime", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_crime_new", "Magazine_Crime_NewBulk", "Base.Magazine_Crime_New", "magazine crime new", "Magazine_Crime_New", wsm="Magazine_Crime_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_fashion", "Magazine_FashionBulk", "Base.Magazine_Fashion", "magazine fashion", "Magazine_Fashion", wsm="Magazine_Fashion", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_fashion_new", "Magazine_Fashion_NewBulk", "Base.Magazine_Fashion_New", "magazine fashion new", "Magazine_Fashion_New", wsm="Magazine_Fashion_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_firearm", "Magazine_FirearmBulk", "Base.Magazine_Firearm", "magazine firearm", "Magazine_Firearm", wsm="Magazine_Firearm", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_firearm_new", "Magazine_Firearm_NewBulk", "Base.Magazine_Firearm_New", "magazine firearm new", "Magazine_Firearm_New", wsm="Magazine_Firearm_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_gaming", "Magazine_GamingBulk", "Base.Magazine_Gaming", "magazine gaming", "Magazine_Gaming", wsm="Magazine_Gaming", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_gaming_new", "Magazine_Gaming_NewBulk", "Base.Magazine_Gaming_New", "magazine gaming new", "Magazine_Gaming_New", wsm="Magazine_Gaming_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_golf", "Magazine_GolfBulk", "Base.Magazine_Golf", "magazine golf", "Magazine_Golf", wsm="Magazine_Golf", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_golf_new", "Magazine_Golf_NewBulk", "Base.Magazine_Golf_New", "magazine golf new", "Magazine_Golf_New", wsm="Magazine_Golf_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_health", "Magazine_HealthBulk", "Base.Magazine_Health", "magazine health", "Magazine_Health", wsm="Magazine_Health", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_health_new", "Magazine_Health_NewBulk", "Base.Magazine_Health_New", "magazine health new", "Magazine_Health_New", wsm="Magazine_Health_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_hobby", "Magazine_HobbyBulk", "Base.Magazine_Hobby", "magazine hobby", "Magazine_Hobby", wsm="Magazine_Hobby", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_hobby_new", "Magazine_Hobby_NewBulk", "Base.Magazine_Hobby_New", "magazine hobby new", "Magazine_Hobby_New", wsm="Magazine_Hobby_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_horror", "Magazine_HorrorBulk", "Base.Magazine_Horror", "magazine horror", "Magazine_Horror", wsm="Magazine_Horror", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_horror_new", "Magazine_Horror_NewBulk", "Base.Magazine_Horror_New", "magazine horror new", "Magazine_Horror_New", wsm="Magazine_Horror_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_humor", "Magazine_HumorBulk", "Base.Magazine_Humor", "magazine humor", "Magazine_Humor", wsm="Magazine_Humor", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_humor_new", "Magazine_Humor_NewBulk", "Base.Magazine_Humor_New", "magazine humor new", "Magazine_Humor_New", wsm="Magazine_Humor_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_military", "Magazine_MilitaryBulk", "Base.Magazine_Military", "magazine military", "Magazine_Military", wsm="Magazine_Military", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_military_new", "Magazine_Military_NewBulk", "Base.Magazine_Military_New", "magazine military new", "Magazine_Military_New", wsm="Magazine_Military_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_music", "Magazine_MusicBulk", "Base.Magazine_Music", "magazine music", "Magazine_Music", wsm="Magazine_Music", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_music_new", "Magazine_Music_NewBulk", "Base.Magazine_Music_New", "magazine music new", "Magazine_Music_New", wsm="Magazine_Music_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_new", "Magazine_NewBulk", "Base.Magazine_New", "magazine new", "Magazine_New", wsm="Magazine_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_outdoors", "Magazine_OutdoorsBulk", "Base.Magazine_Outdoors", "magazine outdoors", "Magazine_Outdoors", wsm="Magazine_Outdoors", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_outdoors_new", "Magazine_Outdoors_NewBulk", "Base.Magazine_Outdoors_New", "magazine outdoors new", "Magazine_Outdoors_New", wsm="Magazine_Outdoors_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_police", "Magazine_PoliceBulk", "Base.Magazine_Police", "magazine police", "Magazine_Police", wsm="Magazine_Police", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_police_new", "Magazine_Police_NewBulk", "Base.Magazine_Police_New", "magazine police new", "Magazine_Police_New", wsm="Magazine_Police_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_popular", "Magazine_PopularBulk", "Base.Magazine_Popular", "magazine popular", "Magazine_Popular", wsm="Magazine_Popular", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_popular_new", "Magazine_Popular_NewBulk", "Base.Magazine_Popular_New", "magazine popular new", "Magazine_Popular_New", wsm="Magazine_Popular_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_rich", "Magazine_RichBulk", "Base.Magazine_Rich", "magazine rich", "Magazine_Rich", wsm="Magazine_Rich", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_rich_new", "Magazine_Rich_NewBulk", "Base.Magazine_Rich_New", "magazine rich new", "Magazine_Rich_New", wsm="Magazine_Rich_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_science", "Magazine_ScienceBulk", "Base.Magazine_Science", "magazine science", "Magazine_Science", wsm="Magazine_Science", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_science_new", "Magazine_Science_NewBulk", "Base.Magazine_Science_New", "magazine science new", "Magazine_Science_New", wsm="Magazine_Science_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_sports", "Magazine_SportsBulk", "Base.Magazine_Sports", "magazine sports", "Magazine_Sports", wsm="Magazine_Sports", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_sports_new", "Magazine_Sports_NewBulk", "Base.Magazine_Sports_New", "magazine sports new", "Magazine_Sports_New", wsm="Magazine_Sports_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_tech", "Magazine_TechBulk", "Base.Magazine_Tech", "magazine tech", "Magazine_Tech", wsm="Magazine_Tech", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_tech_new", "Magazine_Tech_NewBulk", "Base.Magazine_Tech_New", "magazine tech new", "Magazine_Tech_New", wsm="Magazine_Tech_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_teens", "Magazine_TeensBulk", "Base.Magazine_Teens", "magazine teens", "Magazine_Teens", wsm="Magazine_Teens", display_category="Literature", item_type="base:literature"),
    _mat("w2_magazine_teens_new", "Magazine_Teens_NewBulk", "Base.Magazine_Teens_New", "magazine teens new", "Magazine_Teens_New", wsm="Magazine_Teens_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_menu_card", "MenuCardBulk", "Base.MenuCard", "menu card", "MenuCard", wsm="MenuCard", display_category="Literature", item_type="base:literature"),
    _mat("w2_newspaper_dispatch_new", "Newspaper_Dispatch_NewBulk", "Base.Newspaper_Dispatch_New", "newspaper dispatch new", "Newspaper_Dispatch_New", wsm="Newspaper_Dispatch_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_newspaper_herald_new", "Newspaper_Herald_NewBulk", "Base.Newspaper_Herald_New", "newspaper herald new", "Newspaper_Herald_New", wsm="Newspaper_Herald_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_newspaper_knews_new", "Newspaper_Knews_NewBulk", "Base.Newspaper_Knews_New", "newspaper knews new", "Newspaper_Knews_New", wsm="Newspaper_Knews_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_newspaper_new", "Newspaper_NewBulk", "Base.Newspaper_New", "newspaper new", "Newspaper_New", wsm="Newspaper_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_newspaper_recent", "Newspaper_RecentBulk", "Base.Newspaper_Recent", "newspaper recent", "Newspaper_Recent", wsm="Newspaper_Recent", display_category="Literature", item_type="base:literature"),
    _mat("w2_newspaper_times_new", "Newspaper_Times_NewBulk", "Base.Newspaper_Times_New", "newspaper times new", "Newspaper_Times_New", wsm="Newspaper_Times_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_notepad", "NotepadBulk", "Base.Notepad", "notepad", "Notepad", wsm="Notepad", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback", "PaperbackBulk", "Base.Paperback", "paperback", "Paperback", wsm="Paperback", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_adventure_non_fiction", "Paperback_AdventureNonFictionBulk", "Base.Paperback_AdventureNonFiction", "paperback adventure non fiction", "Paperback_AdventureNonFiction", wsm="Paperback_AdventureNonFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_art", "Paperback_ArtBulk", "Base.Paperback_Art", "paperback art", "Paperback_Art", wsm="Paperback_Art", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_baseball", "Paperback_BaseballBulk", "Base.Paperback_Baseball", "paperback baseball", "Paperback_Baseball", wsm="Paperback_Baseball", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_bible", "Paperback_BibleBulk", "Base.Paperback_Bible", "paperback bible", "Paperback_Bible", wsm="Paperback_Bible", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_biography", "Paperback_BiographyBulk", "Base.Paperback_Biography", "paperback biography", "Paperback_Biography", wsm="Paperback_Biography", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_business", "Paperback_BusinessBulk", "Base.Paperback_Business", "paperback business", "Paperback_Business", wsm="Paperback_Business", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_childs", "Paperback_ChildsBulk", "Base.Paperback_Childs", "paperback childs", "Paperback_Childs", wsm="Paperback_Childs", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_cinema", "Paperback_CinemaBulk", "Base.Paperback_Cinema", "paperback cinema", "Paperback_Cinema", wsm="Paperback_Cinema", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_classic", "Paperback_ClassicBulk", "Base.Paperback_Classic", "paperback classic", "Paperback_Classic", wsm="Paperback_Classic", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_classic_fiction", "Paperback_ClassicFictionBulk", "Base.Paperback_ClassicFiction", "paperback classic fiction", "Paperback_ClassicFiction", wsm="Paperback_ClassicFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_classic_nonfiction", "Paperback_ClassicNonfictionBulk", "Base.Paperback_ClassicNonfiction", "paperback classic nonfiction", "Paperback_ClassicNonfiction", wsm="Paperback_ClassicNonfiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_computer", "Paperback_ComputerBulk", "Base.Paperback_Computer", "paperback computer", "Paperback_Computer", wsm="Paperback_Computer", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_conspiracy", "Paperback_ConspiracyBulk", "Base.Paperback_Conspiracy", "paperback conspiracy", "Paperback_Conspiracy", wsm="Paperback_Conspiracy", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_crime_fiction", "Paperback_CrimeFictionBulk", "Base.Paperback_CrimeFiction", "paperback crime fiction", "Paperback_CrimeFiction", wsm="Paperback_CrimeFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_diet", "Paperback_DietBulk", "Base.Paperback_Diet", "paperback diet", "Paperback_Diet", wsm="Paperback_Diet", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_fantasy", "Paperback_FantasyBulk", "Base.Paperback_Fantasy", "paperback fantasy", "Paperback_Fantasy", wsm="Paperback_Fantasy", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_fashion", "Paperback_FashionBulk", "Base.Paperback_Fashion", "paperback fashion", "Paperback_Fashion", wsm="Paperback_Fashion", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_fiction", "Paperback_FictionBulk", "Base.Paperback_Fiction", "paperback fiction", "Paperback_Fiction", wsm="Paperback_Fiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_golf", "Paperback_GolfBulk", "Base.Paperback_Golf", "paperback golf", "Paperback_Golf", wsm="Paperback_Golf", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_hass", "Paperback_HassBulk", "Base.Paperback_Hass", "paperback hass", "Paperback_Hass", wsm="Paperback_Hass", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_history", "Paperback_HistoryBulk", "Base.Paperback_History", "paperback history", "Paperback_History", wsm="Paperback_History", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_horror", "Paperback_HorrorBulk", "Base.Paperback_Horror", "paperback horror", "Paperback_Horror", wsm="Paperback_Horror", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_legal", "Paperback_LegalBulk", "Base.Paperback_Legal", "paperback legal", "Paperback_Legal", wsm="Paperback_Legal", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_literary_fiction", "Paperback_LiteraryFictionBulk", "Base.Paperback_LiteraryFiction", "paperback literary fiction", "Paperback_LiteraryFiction", wsm="Paperback_LiteraryFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_medical", "Paperback_MedicalBulk", "Base.Paperback_Medical", "paperback medical", "Paperback_Medical", wsm="Paperback_Medical", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_military", "Paperback_MilitaryBulk", "Base.Paperback_Military", "paperback military", "Paperback_Military", wsm="Paperback_Military", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_military_history", "Paperback_MilitaryHistoryBulk", "Base.Paperback_MilitaryHistory", "paperback military history", "Paperback_MilitaryHistory", wsm="Paperback_MilitaryHistory", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_music", "Paperback_MusicBulk", "Base.Paperback_Music", "paperback music", "Paperback_Music", wsm="Paperback_Music", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_nature", "Paperback_NatureBulk", "Base.Paperback_Nature", "paperback nature", "Paperback_Nature", wsm="Paperback_Nature", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_new_age", "Paperback_NewAgeBulk", "Base.Paperback_NewAge", "paperback new age", "Paperback_NewAge", wsm="Paperback_NewAge", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_occult", "Paperback_OccultBulk", "Base.Paperback_Occult", "paperback occult", "Paperback_Occult", wsm="Paperback_Occult", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_philosophy", "Paperback_PhilosophyBulk", "Base.Paperback_Philosophy", "paperback philosophy", "Paperback_Philosophy", wsm="Paperback_Philosophy", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_play", "Paperback_PlayBulk", "Base.Paperback_Play", "paperback play", "Paperback_Play", wsm="Paperback_Play", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_policing", "Paperback_PolicingBulk", "Base.Paperback_Policing", "paperback policing", "Paperback_Policing", wsm="Paperback_Policing", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_politics", "Paperback_PoliticsBulk", "Base.Paperback_Politics", "paperback politics", "Paperback_Politics", wsm="Paperback_Politics", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_poor", "Paperback_PoorBulk", "Base.Paperback_Poor", "paperback poor", "Paperback_Poor", wsm="Paperback_Poor", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_quackery", "Paperback_QuackeryBulk", "Base.Paperback_Quackery", "paperback quackery", "Paperback_Quackery", wsm="Paperback_Quackery", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_quigley", "Paperback_QuigleyBulk", "Base.Paperback_Quigley", "paperback quigley", "Paperback_Quigley", wsm="Paperback_Quigley", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_relationship", "Paperback_RelationshipBulk", "Base.Paperback_Relationship", "paperback relationship", "Paperback_Relationship", wsm="Paperback_Relationship", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_religion", "Paperback_ReligionBulk", "Base.Paperback_Religion", "paperback religion", "Paperback_Religion", wsm="Paperback_Religion", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_rich", "Paperback_RichBulk", "Base.Paperback_Rich", "paperback rich", "Paperback_Rich", wsm="Paperback_Rich", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_romance", "Paperback_RomanceBulk", "Base.Paperback_Romance", "paperback romance", "Paperback_Romance", wsm="Paperback_Romance", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_sad_non_fiction", "Paperback_SadNonFictionBulk", "Base.Paperback_SadNonFiction", "paperback sad non fiction", "Paperback_SadNonFiction", wsm="Paperback_SadNonFiction", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_scary", "Paperback_ScaryBulk", "Base.Paperback_Scary", "paperback scary", "Paperback_Scary", wsm="Paperback_Scary", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_sci_fi", "Paperback_SciFiBulk", "Base.Paperback_SciFi", "paperback sci fi", "Paperback_SciFi", wsm="Paperback_SciFi", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_science", "Paperback_ScienceBulk", "Base.Paperback_Science", "paperback science", "Paperback_Science", wsm="Paperback_Science", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_self_help", "Paperback_SelfHelpBulk", "Base.Paperback_SelfHelp", "paperback self help", "Paperback_SelfHelp", wsm="Paperback_SelfHelp", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_sexy", "Paperback_SexyBulk", "Base.Paperback_Sexy", "paperback sexy", "Paperback_Sexy", wsm="Paperback_Sexy", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_sports", "Paperback_SportsBulk", "Base.Paperback_Sports", "paperback sports", "Paperback_Sports", wsm="Paperback_Sports", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_teens", "Paperback_TeensBulk", "Base.Paperback_Teens", "paperback teens", "Paperback_Teens", wsm="Paperback_Teens", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_thriller", "Paperback_ThrillerBulk", "Base.Paperback_Thriller", "paperback thriller", "Paperback_Thriller", wsm="Paperback_Thriller", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_travel", "Paperback_TravelBulk", "Base.Paperback_Travel", "paperback travel", "Paperback_Travel", wsm="Paperback_Travel", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_true_crime", "Paperback_TrueCrimeBulk", "Base.Paperback_TrueCrime", "paperback true crime", "Paperback_TrueCrime", wsm="Paperback_TrueCrime", display_category="Literature", item_type="base:literature"),
    _mat("w2_paperback_western", "Paperback_WesternBulk", "Base.Paperback_Western", "paperback western", "Paperback_Western", wsm="Paperback_Western", display_category="Literature", item_type="base:literature"),
    _mat("w2_phonebook", "PhonebookBulk", "Base.Phonebook", "phonebook", "Phonebook", wsm="Phonebook", display_category="Literature", item_type="base:literature"),
    _mat("w2_photo_book", "PhotoBookBulk", "Base.PhotoBook", "photo book", "PhotoBook", wsm="PhotoBook", display_category="Literature", item_type="base:literature"),
    _mat("w2_rpgmanual", "RPGmanualBulk", "Base.RPGmanual", "rpgmanual", "RPGmanual", wsm="RPGmanual", display_category="Literature", item_type="base:literature"),
    _mat("w2_tvmagazine", "TVMagazineBulk", "Base.TVMagazine", "tvmagazine", "TVMagazine", wsm="TVMagazine", display_category="Literature", item_type="base:literature"),
    _mat("w2_tvmagazine_new", "TVMagazine_NewBulk", "Base.TVMagazine_New", "tvmagazine new", "TVMagazine_New", wsm="TVMagazine_New", display_category="Literature", item_type="base:literature"),
    _mat("w2_ceramic_crucible_small_iron", "CeramicCrucibleSmall_IronBulk", "Base.CeramicCrucibleSmall_Iron", "ceramic crucible small iron", "CeramicCrucibleSmall_Iron", wsm="CeramicCrucibleSmall_Iron", item_type="base:drainable"),
    _mat("w2_ceramic_crucible_small_steel", "CeramicCrucibleSmall_SteelBulk", "Base.CeramicCrucibleSmall_Steel", "ceramic crucible small steel", "CeramicCrucibleSmall_Steel", wsm="CeramicCrucibleSmall_Steel", item_type="base:drainable"),
    _mat("w2_ceramic_crucible_with_glass", "CeramicCrucibleWithGlassBulk", "Base.CeramicCrucibleWithGlass", "ceramic crucible with glass", "CeramicCrucibleWithGlass", wsm="CeramicCrucibleWithGlass", item_type="base:drainable"),
    _mat("w2_industrial_dye", "IndustrialDyeBulk", "Base.IndustrialDye", "industrial dye", "IndustrialDye", wsm="IndustrialDye"),
    _mat("w2_propane_tank", "PropaneTankBulk", "Base.PropaneTank", "propane tank", "PropaneTank", wsm="PropaneTank", item_type="base:drainable"),
    _mat("w2_amethyst", "AmethystBulk", "Base.Amethyst", "amethyst", "Amethyst", wsm="Amethyst", display_category="Memento"),
    _mat("w2_badge", "BadgeBulk", "Base.Badge", "badge", "Badge", wsm="Badge", display_category="Memento"),
    _mat("w2_bob_pic", "BobPicBulk", "Base.BobPic", "bob pic", "BobPic", wsm="BobPic", display_category="Memento"),
    _mat("w2_bricktoys", "BricktoysBulk", "Base.Bricktoys", "bricktoys", "Bricktoys", wsm="Bricktoys", display_category="Memento"),
    _mat("w2_camera_expensive", "CameraExpensiveBulk", "Base.CameraExpensive", "camera expensive", "CameraExpensive", wsm="CameraExpensive", display_category="Memento"),
    _mat("w2_cap_gun_cap", "CapGunCapBulk", "Base.CapGunCap", "cap gun cap", "CapGunCap", wsm="CapGunCap", display_category="Memento"),
    _mat("w2_card_birthday", "Card_BirthdayBulk", "Base.Card_Birthday", "card birthday", "Card_Birthday", wsm="Card_Birthday", display_category="Literature", item_type="base:literature"),
    _mat("w2_card_christmas", "Card_ChristmasBulk", "Base.Card_Christmas", "card christmas", "Card_Christmas", wsm="Card_Christmas", display_category="Literature", item_type="base:literature"),
    _mat("w2_card_easter", "Card_EasterBulk", "Base.Card_Easter", "card easter", "Card_Easter", wsm="Card_Easter", display_category="Literature", item_type="base:literature"),
    _mat("w2_card_halloween", "Card_HalloweenBulk", "Base.Card_Halloween", "card halloween", "Card_Halloween", wsm="Card_Halloween", display_category="Literature", item_type="base:literature"),
    _mat("w2_card_hanukkah", "Card_HanukkahBulk", "Base.Card_Hanukkah", "card hanukkah", "Card_Hanukkah", wsm="Card_Hanukkah", display_category="Literature", item_type="base:literature"),
    _mat("w2_card_lunar_year", "Card_LunarYearBulk", "Base.Card_LunarYear", "card lunar year", "Card_LunarYear", wsm="Card_LunarYear", display_category="Literature", item_type="base:literature"),
    _mat("w2_card_st_patrick", "Card_StPatrickBulk", "Base.Card_StPatrick", "card st patrick", "Card_StPatrick", wsm="Card_StPatrick", display_category="Literature", item_type="base:literature"),
    _mat("w2_card_sympathy", "Card_SympathyBulk", "Base.Card_Sympathy", "card sympathy", "Card_Sympathy", wsm="Card_Sympathy", display_category="Literature", item_type="base:literature"),
    _mat("w2_card_valentine", "Card_ValentineBulk", "Base.Card_Valentine", "card valentine", "Card_Valentine", wsm="Card_Valentine", display_category="Literature", item_type="base:literature"),
    _mat("w2_cat_toy", "CatToyBulk", "Base.CatToy", "cat toy", "CatToy", wsm="CatToy", display_category="Memento"),
    _mat("w2_chris_pic", "ChrisPicBulk", "Base.ChrisPic", "chris pic", "ChrisPic", wsm="ChrisPic", display_category="Memento"),
    _mat("w2_christmas_hanging", "ChristmasHangingBulk", "Base.ChristmasHanging", "christmas hanging", "ChristmasHanging", wsm="ChristmasHanging", display_category="Memento"),
    _mat("w2_christmas_ornament_gold1", "ChristmasOrnament_Gold1Bulk", "Base.ChristmasOrnament_Gold1", "christmas ornament gold1", "ChristmasOrnament_Gold1", wsm="ChristmasOrnament_Gold1", display_category="Memento"),
    _mat("w2_christmas_ornament_gold2", "ChristmasOrnament_Gold2Bulk", "Base.ChristmasOrnament_Gold2", "christmas ornament gold2", "ChristmasOrnament_Gold2", wsm="ChristmasOrnament_Gold2", display_category="Memento"),
    _mat("w2_christmas_ornament_gold3", "ChristmasOrnament_Gold3Bulk", "Base.ChristmasOrnament_Gold3", "christmas ornament gold3", "ChristmasOrnament_Gold3", wsm="ChristmasOrnament_Gold3", display_category="Memento"),
    _mat("w2_christmas_ornament_green1", "ChristmasOrnament_Green1Bulk", "Base.ChristmasOrnament_Green1", "christmas ornament green1", "ChristmasOrnament_Green1", wsm="ChristmasOrnament_Green1", display_category="Memento"),
    _mat("w2_christmas_ornament_green2", "ChristmasOrnament_Green2Bulk", "Base.ChristmasOrnament_Green2", "christmas ornament green2", "ChristmasOrnament_Green2", wsm="ChristmasOrnament_Green2", display_category="Memento"),
    _mat("w2_christmas_ornament_green3", "ChristmasOrnament_Green3Bulk", "Base.ChristmasOrnament_Green3", "christmas ornament green3", "ChristmasOrnament_Green3", wsm="ChristmasOrnament_Green3", display_category="Memento"),
    _mat("w2_christmas_ornament_red1", "ChristmasOrnament_Red1Bulk", "Base.ChristmasOrnament_Red1", "christmas ornament red1", "ChristmasOrnament_Red1", wsm="ChristmasOrnament_Red1", display_category="Memento"),
    _mat("w2_christmas_ornament_red2", "ChristmasOrnament_Red2Bulk", "Base.ChristmasOrnament_Red2", "christmas ornament red2", "ChristmasOrnament_Red2", wsm="ChristmasOrnament_Red2", display_category="Memento"),
    _mat("w2_christmas_ornament_red3", "ChristmasOrnament_Red3Bulk", "Base.ChristmasOrnament_Red3", "christmas ornament red3", "ChristmasOrnament_Red3", wsm="ChristmasOrnament_Red3", display_category="Memento"),
    _mat("w2_christmas_wreath", "ChristmasWreathBulk", "Base.ChristmasWreath", "christmas wreath", "ChristmasWreath", wsm="ChristmasWreath", display_category="Memento"),
    _mat("w2_cortman_pic", "CortmanPicBulk", "Base.CortmanPic", "cortman pic", "CortmanPic", wsm="CortmanPic", display_category="Memento"),
    _mat("w2_crystal", "CrystalBulk", "Base.Crystal", "crystal", "Crystal", wsm="Crystal", display_category="Memento"),
    _mat("w2_crystal_large", "Crystal_LargeBulk", "Base.Crystal_Large", "crystal large", "Crystal_Large", wsm="Crystal_Large", display_category="Memento"),
    _mat("w2_cube", "CubeBulk", "Base.Cube", "cube", "Cube", wsm="Cube", display_category="Memento"),
    _mat("w2_diamond", "DiamondBulk", "Base.Diamond", "diamond", "Diamond", wsm="Diamond", display_category="Memento"),
    _mat("w2_dice_00", "Dice_00Bulk", "Base.Dice_00", "dice 00", "Dice_00", wsm="Dice_00", display_category="Memento"),
    _mat("w2_dice_10", "Dice_10Bulk", "Base.Dice_10", "dice 10", "Dice_10", wsm="Dice_10", display_category="Memento"),
    _mat("w2_dice_12", "Dice_12Bulk", "Base.Dice_12", "dice 12", "Dice_12", wsm="Dice_12", display_category="Memento"),
    _mat("w2_dice_20", "Dice_20Bulk", "Base.Dice_20", "dice 20", "Dice_20", wsm="Dice_20", display_category="Memento"),
    _mat("w2_dice_4", "Dice_4Bulk", "Base.Dice_4", "dice 4", "Dice_4", wsm="Dice_4", display_category="Memento"),
    _mat("w2_dice_6", "Dice_6Bulk", "Base.Dice_6", "dice 6", "Dice_6", wsm="Dice_6", display_category="Memento"),
    _mat("w2_dice_8", "Dice_8Bulk", "Base.Dice_8", "dice 8", "Dice_8", wsm="Dice_8", display_category="Memento"),
    _mat("w2_dog_chew", "DogChewBulk", "Base.DogChew", "dog chew", "DogChew", wsm="DogChew", display_category="Memento"),
    _mat("w2_dog_tag_pet", "DogTag_PetBulk", "Base.DogTag_Pet", "dog tag pet", "DogTag_Pet", wsm="DogTag_Pet", display_category="Memento"),
    _mat("w2_doll", "DollBulk", "Base.Doll", "doll", "Doll", wsm="Doll", display_category="Memento"),
    _mat("w2_doodle", "DoodleBulk", "Base.Doodle", "doodle", "Doodle", wsm="Doodle", display_category="Literature", item_type="base:literature"),
    _mat("w2_doodle_kids", "DoodleKidsBulk", "Base.DoodleKids", "doodle kids", "DoodleKids", wsm="DoodleKids", display_category="Literature", item_type="base:literature"),
    _mat("w2_emerald", "EmeraldBulk", "Base.Emerald", "emerald", "Emerald", wsm="Emerald", display_category="Memento"),
    _mat("w2_flask", "FlaskBulk", "Base.Flask", "flask", "Flask", wsm="Flask", display_category="Memento"),
    _mat("w2_goblet", "GobletBulk", "Base.Goblet", "goblet", "Goblet", wsm="Goblet", display_category="Memento"),
    _mat("w2_goblet_gold", "Goblet_GoldBulk", "Base.Goblet_Gold", "goblet gold", "Goblet_Gold", wsm="Goblet_Gold", display_category="Memento"),
    _mat("w2_goblet_silver", "Goblet_SilverBulk", "Base.Goblet_Silver", "goblet silver", "Goblet_Silver", wsm="Goblet_Silver", display_category="Memento"),
    _mat("w2_goblet_wood", "Goblet_WoodBulk", "Base.Goblet_Wood", "goblet wood", "Goblet_Wood", wsm="Goblet_Wood", display_category="Memento"),
    _mat("w2_gold_coin", "GoldCoinBulk", "Base.GoldCoin", "gold coin", "GoldCoin", wsm="GoldCoin", display_category="Memento"),
    _mat("w2_hank_pic", "HankPicBulk", "Base.HankPic", "hank pic", "HankPic", wsm="HankPic", display_category="Memento"),
    _mat("w2_hominid_skull", "Hominid_SkullBulk", "Base.Hominid_Skull", "hominid skull", "Hominid_Skull", wsm="Hominid_Skull", display_category="Memento"),
    _mat("w2_hominid_skull_fragment", "Hominid_Skull_FragmentBulk", "Base.Hominid_Skull_Fragment", "hominid skull fragment", "Hominid_Skull_Fragment", wsm="Hominid_Skull_Fragment", display_category="Memento"),
    _mat("w2_hominid_skull_partial", "Hominid_Skull_PartialBulk", "Base.Hominid_Skull_Partial", "hominid skull partial", "Hominid_Skull_Partial", wsm="Hominid_Skull_Partial", display_category="Memento"),
    _mat("w2_james_pic", "JamesPicBulk", "Base.JamesPic", "james pic", "JamesPic", wsm="JamesPic", display_category="Memento"),
    _mat("w2_katana_handle", "Katana_HandleBulk", "Base.Katana_Handle", "katana handle", "Katana_Handle", wsm="Katana_Handle", display_category="Memento"),
    _mat("w2_kate_pic", "KatePicBulk", "Base.KatePic", "kate pic", "KatePic", wsm="KatePic", display_category="Memento"),
    _mat("w2_marianne_pic", "MariannePicBulk", "Base.MariannePic", "marianne pic", "MariannePic", wsm="MariannePic", display_category="Memento"),
    _mat("w2_military_medal", "MilitaryMedalBulk", "Base.MilitaryMedal", "military medal", "MilitaryMedal", wsm="MilitaryMedal", display_category="Memento"),
    _mat("w2_mug_spiffo", "MugSpiffoBulk", "Base.MugSpiffo", "mug spiffo", "MugSpiffo", wsm="MugSpiffo", display_category="Memento"),
    _mat("w2_ouja_board", "OujaBoardBulk", "Base.OujaBoard", "ouja board", "OujaBoard", wsm="OujaBoard", display_category="Memento"),
    _mat("w2_photo", "PhotoBulk", "Base.Photo", "photo", "Photo", wsm="Photo", display_category="Literature", item_type="base:literature"),
    _mat("w2_photo_hass", "Photo_HassBulk", "Base.Photo_Hass", "photo hass", "Photo_Hass", wsm="Photo_Hass", display_category="Literature", item_type="base:literature"),
    _mat("w2_photo_racy", "Photo_RacyBulk", "Base.Photo_Racy", "photo racy", "Photo_Racy", wsm="Photo_Racy", display_category="Literature", item_type="base:literature"),
    _mat("w2_photo_secret", "Photo_SecretBulk", "Base.Photo_Secret", "photo secret", "Photo_Secret", wsm="Photo_Secret", display_category="Literature", item_type="base:literature"),
    _mat("w2_photo_very_old", "Photo_VeryOldBulk", "Base.Photo_VeryOld", "photo very old", "Photo_VeryOld", wsm="Photo_VeryOld", display_category="Literature", item_type="base:literature"),
    _mat("w2_pillow_happyface", "Pillow_HappyfaceBulk", "Base.Pillow_Happyface", "pillow happyface", "Pillow_Happyface", wsm="Pillow_Happyface", display_category="Memento"),
    _mat("w2_pillow_heart", "Pillow_HeartBulk", "Base.Pillow_Heart", "pillow heart", "Pillow_Heart", wsm="Pillow_Heart", display_category="Memento"),
    _mat("w2_pillow_star", "Pillow_StarBulk", "Base.Pillow_Star", "pillow star", "Pillow_Star", wsm="Pillow_Star", display_category="Memento"),
    _mat("w2_postcard", "PostcardBulk", "Base.Postcard", "postcard", "Postcard", wsm="Postcard", display_category="Literature", item_type="base:literature"),
    _mat("w2_ruby", "RubyBulk", "Base.Ruby", "ruby", "Ruby", wsm="Ruby", display_category="Memento"),
    _mat("w2_sapphire", "SapphireBulk", "Base.Sapphire", "sapphire", "Sapphire", wsm="Sapphire", display_category="Memento"),
    _mat("w2_silver_coin", "SilverCoinBulk", "Base.SilverCoin", "silver coin", "SilverCoin", wsm="SilverCoin", display_category="Memento"),
    _mat("w2_snow_globe", "SnowGlobeBulk", "Base.SnowGlobe", "snow globe", "SnowGlobe", wsm="SnowGlobe", display_category="Memento"),
    _mat("w2_specimen_brain", "Specimen_BrainBulk", "Base.Specimen_Brain", "specimen brain", "Specimen_Brain", wsm="Specimen_Brain", display_category="Memento"),
    _mat("w2_specimen_fetal_calf", "Specimen_FetalCalfBulk", "Base.Specimen_FetalCalf", "specimen fetal calf", "Specimen_FetalCalf", wsm="Specimen_FetalCalf", display_category="Memento"),
    _mat("w2_specimen_fetal_lamb", "Specimen_FetalLambBulk", "Base.Specimen_FetalLamb", "specimen fetal lamb", "Specimen_FetalLamb", wsm="Specimen_FetalLamb", display_category="Memento"),
    _mat("w2_specimen_fetal_piglet", "Specimen_FetalPigletBulk", "Base.Specimen_FetalPiglet", "specimen fetal piglet", "Specimen_FetalPiglet", wsm="Specimen_FetalPiglet", display_category="Memento"),
    _mat("w2_specimen_minerals", "Specimen_MineralsBulk", "Base.Specimen_Minerals", "specimen minerals", "Specimen_Minerals", wsm="Specimen_Minerals", display_category="Memento"),
    _mat("w2_specimen_octopus", "Specimen_OctopusBulk", "Base.Specimen_Octopus", "specimen octopus", "Specimen_Octopus", wsm="Specimen_Octopus", display_category="Memento"),
    _mat("w2_specimen_tapeworm", "Specimen_TapewormBulk", "Base.Specimen_Tapeworm", "specimen tapeworm", "Specimen_Tapeworm", wsm="Specimen_Tapeworm", display_category="Memento"),
    _mat("w2_suspicious_package", "SuspiciousPackageBulk", "Base.SuspiciousPackage", "suspicious package", "SuspiciousPackage", wsm="SuspiciousPackage", display_category="Memento"),
    _mat("w2_tarot_card_deck", "TarotCardDeckBulk", "Base.TarotCardDeck", "tarot card deck", "TarotCardDeck", wsm="TarotCardDeck", display_category="Memento"),
    _mat("w2_toy_badge", "ToyBadgeBulk", "Base.ToyBadge", "toy badge", "ToyBadge", wsm="ToyBadge", display_category="Memento"),
    _mat("w2_toy_car", "ToyCarBulk", "Base.ToyCar", "toy car", "ToyCar", wsm="ToyCar", display_category="Memento"),
    _mat("w2_toy_plane", "ToyPlaneBulk", "Base.ToyPlane", "toy plane", "ToyPlane", wsm="ToyPlane", display_category="Memento"),
    _mat("w2_trophy_bronze", "TrophyBronzeBulk", "Base.TrophyBronze", "trophy bronze", "TrophyBronze", wsm="TrophyBronze", display_category="Memento"),
    _mat("w2_trophy_gold", "TrophyGoldBulk", "Base.TrophyGold", "trophy gold", "TrophyGold", wsm="TrophyGold", display_category="Memento"),
    _mat("w2_trophy_silver", "TrophySilverBulk", "Base.TrophySilver", "trophy silver", "TrophySilver", wsm="TrophySilver", display_category="Memento"),
    _mat("w2_yoyo", "YoyoBulk", "Base.Yoyo", "yoyo", "Yoyo", wsm="Yoyo", display_category="Memento"),
    _mat("w2_awl", "AwlBulk", "Base.Awl", "awl", "Awl", wsm="Awl", display_category="Tool"),
    _mat("w2_awl_bone", "Awl_BoneBulk", "Base.Awl_Bone", "awl bone", "Awl_Bone", wsm="Awl_Bone", display_category="Tool"),
    _mat("w2_awl_stone", "Awl_StoneBulk", "Base.Awl_Stone", "awl stone", "Awl_Stone", wsm="Awl_Stone", display_category="Tool"),
    _mat("w2_blow_torch", "BlowTorchBulk", "Base.BlowTorch", "blow torch", "BlowTorch", wsm="BlowTorch", display_category="Tool", item_type="base:drainable"),
    _mat("w2_brush", "BrushBulk", "Base.Brush", "brush", "Brush", wsm="Brush", display_category="Tool"),
    _mat("w2_bullhorn", "BullhornBulk", "Base.Bullhorn", "bullhorn", "Bullhorn", wsm="Bullhorn", display_category="Tool", item_type="base:drainable"),
    _mat("w2_calipers", "CalipersBulk", "Base.Calipers", "calipers", "Calipers", wsm="Calipers", display_category="Tool"),
    _mat("w2_clay_tool", "ClayToolBulk", "Base.ClayTool", "clay tool", "ClayTool", wsm="ClayTool", display_category="Tool"),
    _mat("w2_clay_tool_carved", "ClayTool_CarvedBulk", "Base.ClayTool_Carved", "clay tool carved", "ClayTool_Carved", wsm="ClayTool_Carved", display_category="Tool"),
    _mat("w2_crude_saw", "CrudeSawBulk", "Base.CrudeSaw", "crude saw", "CrudeSaw", wsm="CrudeSaw", display_category="Tool"),
    _mat("w2_crude_wooden_tongs", "CrudeWoodenTongsBulk", "Base.CrudeWoodenTongs", "crude wooden tongs", "CrudeWoodenTongs", wsm="CrudeWoodenTongs", display_category="Tool"),
    _mat("w2_fleshing_tool", "Fleshing_ToolBulk", "Base.Fleshing_Tool", "fleshing tool", "Fleshing_Tool", wsm="Fleshing_Tool", display_category="Tool"),
    _mat("w2_fleshing_tool_bone", "Fleshing_Tool_BoneBulk", "Base.Fleshing_Tool_Bone", "fleshing tool bone", "Fleshing_Tool_Bone", wsm="Fleshing_Tool_Bone", display_category="Tool"),
    _mat("w2_funnel", "FunnelBulk", "Base.Funnel", "funnel", "Funnel", wsm="Funnel", display_category="Tool"),
    _mat("w2_garden_saw", "GardenSawBulk", "Base.GardenSaw", "garden saw", "GardenSaw", wsm="GardenSaw", display_category="Tool"),
    _mat("w2_hand_drill", "HandDrillBulk", "Base.HandDrill", "hand drill", "HandDrill", wsm="HandDrill", display_category="Tool"),
    _mat("w2_heading_tool", "HeadingToolBulk", "Base.HeadingTool", "heading tool", "HeadingTool", wsm="HeadingTool", display_category="Tool"),
    _mat("w2_knapping_tool", "KnappingToolBulk", "Base.KnappingTool", "knapping tool", "KnappingTool", wsm="KnappingTool", display_category="Tool"),
    _mat("w2_knitting_needles_wood", "KnittingNeedles_WoodBulk", "Base.KnittingNeedles_Wood", "knitting needles wood", "KnittingNeedles_Wood", wsm="KnittingNeedles_Wood", display_category="Tool"),
    _mat("w2_loupe", "LoupeBulk", "Base.Loupe", "loupe", "Loupe", wsm="Loupe", display_category="Tool"),
    _mat("w2_masons_trowel_wood", "MasonsTrowel_WoodBulk", "Base.MasonsTrowel_Wood", "masons trowel wood", "MasonsTrowel_Wood", wsm="MasonsTrowel_Wood", display_category="Tool"),
    _mat("w2_metalworking_pliers", "MetalworkingPliersBulk", "Base.MetalworkingPliers", "metalworking pliers", "MetalworkingPliers", wsm="MetalworkingPliers", display_category="Tool"),
    _mat("w2_needle", "NeedleBulk", "Base.Needle", "needle", "Needle", wsm="Needle", display_category="Tool"),
    _mat("w2_oil_press", "OilPressBulk", "Base.OilPress", "oil press", "OilPress", wsm="OilPress", display_category="Tool"),
    _mat("w2_old_drill", "OldDrillBulk", "Base.OldDrill", "old drill", "OldDrill", wsm="OldDrill", display_category="Tool"),
    _mat("w2_paintbrush", "PaintbrushBulk", "Base.Paintbrush", "paintbrush", "Paintbrush", wsm="Paintbrush", display_category="Tool"),
    _mat("w2_pliers", "PliersBulk", "Base.Pliers", "pliers", "Pliers", wsm="Pliers", display_category="Tool"),
    _mat("w2_rubber_hose", "RubberHoseBulk", "Base.RubberHose", "rubber hose", "RubberHose", wsm="RubberHose", display_category="Tool"),
    _mat("w2_saw", "SawBulk", "Base.Saw", "saw", "Saw", wsm="Saw", display_category="Tool"),
    _mat("w2_sheep_electric_shears", "SheepElectricShearsBulk", "Base.SheepElectricShears", "sheep electric shears", "SheepElectricShears", wsm="SheepElectricShears", display_category="Tool", item_type="base:drainable"),
    _mat("w2_sheep_shears", "SheepShearsBulk", "Base.SheepShears", "sheep shears", "SheepShears", wsm="SheepShears", display_category="Tool"),
    _mat("w2_sheep_shears_forged", "SheepShearsForgedBulk", "Base.SheepShearsForged", "sheep shears forged", "SheepShearsForged", wsm="SheepShearsForged", display_category="Tool"),
    _mat("w2_small_file_set", "SmallFileSetBulk", "Base.SmallFileSet", "small file set", "SmallFileSet", wsm="SmallFileSet", display_category="Tool"),
    _mat("w2_small_punch_set", "SmallPunchSetBulk", "Base.SmallPunchSet", "small punch set", "SmallPunchSet", wsm="SmallPunchSet", display_category="Tool"),
    _mat("w2_small_saw", "SmallSawBulk", "Base.SmallSaw", "small saw", "SmallSaw", wsm="SmallSaw", display_category="Tool"),
    _mat("w2_steel_wool", "SteelWoolBulk", "Base.SteelWool", "steel wool", "SteelWool", wsm="SteelWool", display_category="Tool", item_type="base:drainable"),
    _mat("w2_stone_chisel", "StoneChiselBulk", "Base.StoneChisel", "stone chisel", "StoneChisel", wsm="StoneChisel", display_category="Tool"),
    _mat("w2_stone_drill", "StoneDrillBulk", "Base.StoneDrill", "stone drill", "StoneDrill", wsm="StoneDrill", display_category="Tool"),
    _mat("w2_thimble", "ThimbleBulk", "Base.Thimble", "thimble", "Thimble", wsm="Thimble", display_category="Tool"),
    _mat("w2_tongs", "TongsBulk", "Base.Tongs", "tongs", "Tongs", wsm="Tongs", display_category="Tool"),
    _mat("w2_vise_grips", "ViseGripsBulk", "Base.ViseGrips", "vise grips", "ViseGrips", wsm="ViseGrips", display_category="Tool"),
    _mat("w2_whetstone", "WhetstoneBulk", "Base.Whetstone", "whetstone", "Whetstone", wsm="Whetstone", display_category="Tool"),
    _mat("w2_zipties", "ZiptiesBulk", "Base.Zipties", "zipties", "Zipties", wsm="Zipties", display_category="Tool", survival_gear=True),
]
